### ISSUE TITLE
dom-test-kit: scopeSelector incorrectly resolves a class that extends another class (not root)

### ISSUE THREAD

**Issue by PeterShershov** [wix/stylable#1031]
When using the `dom-test-kit` to scope a class that extends a class with `scopeSelector`, the value returned is not valid.

For example: 
```css
.classA {
  --st-extends: classB;
}

.classB {}
```

```ts
domUtil.scopeSelector('.classA')
// .mycomponent3669546579__classA\ mycomponent3669546579__classB
```
ref:
https://github.com/wix/stylable/blob/master/packages/dom-test-kit/src/stylable-dom-util.ts#L36
