### ISSUE TITLE
Make it possible to define CSS rules in global scope without a warning

### ISSUE THREAD

**Issue by alisey** [wix/stylable#1049]
```
WARNING in Stylable: unscoped element "html" will affect all elements of the same type in the document

> 109 | html { color: red; }
```

For tag selectors the warning isn't even helpful, what else would anyone expect to happen?

It becomes even more annoying when you want to reset user agent styles, define basic typography, or style third-party components. You have to repeat `:global()` over and over again:

```css
:global(html), :global(body), :global(div), :global(span), 50 more { ... }
```

**Suggestion**:
1. Remove the warning completely for tag selectors.
2. Add an option to suppress the warning for class selectors and component root selectors, e.g.:
```css
:import {
    -st-from: './foo.st.css';
    -st-default: Foo;
}

/* warning */
Foo { }

/* no warning */
@st-scope global {
    Foo {}
}
```

`-st-global: '*'` is not a good workaround because it generates a descendant selector, which could affect specificity and performance.
