### ISSUE TITLE
Expose mapping for -st-states

### ISSUE THREAD

**Issue by Scott-MacD** [wix/stylable#1060]
Would it be possible for you guys to expose a mapping of all -st-states, per class, in a stylesheet? Something similar to:

```js
import { stStates } from ./stylesheet.st.css
```

Where if I have a stylesheet like the following:
```css
@namespace "MyComponent";
.root {
    -st-states: toggled, loading;
}
.root:toggled { color: red; }
.root:loading { color: green; }
.root:loading:toggled { color: blue; }

.someInput {
    -st-states: valid, error;
}

.someInput:error { color: red; }
```

Would expose a tree similar to the following?
```js
stStates = {
    root: {
        toggled: "MyComponent--toggled",
        loading: "MyComponent--loading",
    },
    someInput: {
        valid: "MyComponent--valid",
        error: "MyComponent--error"
    }
}
```

I'm building a wrapper around custom elements and looking for a simple mechanism that I can hook into observed attributes to add and remove specific stylable pseudo classes based on those attributes changing. IE, if I set `.loading = true` on my component, it would be nice to have a hook to automatically trigger `this.classList.add(stStates.root.loading)` or something similar. This would help avoid complications about having to keep track of css classes that are outside of the scope of the component, such as when a .root element has layout from a parent component, or when the custom element extends an existing element on the dom on hydration. `cssStates` sort of works here, however unless the behavior is changed, I don't believe there is a way to tell if a state actually exists in the stylesheet or not and I would like to avoid polluting the DOM with every possible property that gets added to a component. This would also be more consistent with the existing mappings for `vars`, `classes`, `stVars`, and `stKeyframes`.

Is this doable or do you guys have any other thoughts on approaches here?

Thank you.
