### ISSUE TITLE
insert mixin in the position it is declared

### ISSUE THREAD

**Issue by idoros** [wix/stylable#11]
* rules are added at the position that the `-st-mixin` is declared
* appended selectors are added directly after the rule-set that the mixin was applied to
* multiple mixins are applied according to the order that they are specified in

CSS API:
```css
.a{
    color:red;
    -st-mixin: golden;
    background:white;
}
.a:hover{
    background:white;
}
```

CSS OUTPUT:
```css
.a{
    color:red;
    color:gold; /* added by golden */
    background:black; /* added by golden */
    background:white;
}
.a:hover{
    color:gold; /* added by golden */
    background:black; /* added by golden */
}
.a:hover{
    background:white;
}
```
