### ISSUE TITLE
compose and extend of CSS class might not work

### ISSUE THREAD

**Issue by barak007** [wix/stylable#113]
```css
@namespace "A";
/*
@selector    .A--root .A--a
@JS value    "A--a"
*/
.a {}
```
```css
@namespace "B";
:imports {
    -st-from: "./a.st.css";
    -st-named: a;
}
/*
@selector    .B--root .B--b
@JS value    "B--b A--a"
*/
.b { -st-compose: a; }
```

Issues:
1. no guarantee that CSS from the imported stylesheet will output to final CSS (only if directly used from JS or imported as theme)
1. when composing classes from none theme we can't suppose the composed `.A--a` is nested under `.A--root`.

consider completely removing root scoping when possible...
