### ISSUE TITLE
-st-from: "<file-path>" should be clickable

### ISSUE THREAD

**Issue by AviVahl** [wix/stylable#1148]
Example:
```css
:import {
    -st-from: "../src/components/style.st.css";
    -st-default: MyStyle;
}
```

when clicking `../src/components/style.st.css`, it should jump to that file.
