### ISSUE TITLE
Add the ability to access inner selector parts without explicitly importing them by name

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1196]
### Problem introduction
A common pattern we see used in Stylable is one where a component can selectively apply classes to some of its inner parts. When trying to customize such a component externally, it is not possible to create an overriding selector without using an explicit named import for the modifier class being targeted.

#### Example
```css
/* a.st.css */
.root {}
.part {}
.modifier {}
```

```css
/* b.st.css */
:import {
  -st-from: './a.st.css';
  -st-default: Comp;
  -st-named: modifier;
}

/* desired result - valid code */
Comp::part .modifier {} /* .a__root .a__part .a__modifier */

/***  invalid cases  ***/
/* error - modifier is not defined as an inner part of ".part" */
Comp::part::modifier {} /* .a__root .a__part::modifier */

/* unwanted output - this would target a recursive sort of structure */
Comp::part Comp::modifier {} /* .a__root .a__part .a__root .a__modifier */
```

What we want to be able to do is access the `.modifier` class through the `Comp` element, but without creating its root class again.

### Possible solution `::-stContext`
`::-stContext` would allow you to provide an existing class or element (with pseudo-elements) that will be used for setting the selector scope, type checking and validation from that point on in the selector. However, those selector parts will not be included in the resulting transpiled code.

#### Example
```css
/* comp1.st.css */
.root {
  -st-state: someState;
}
.otherPart {}
```

```css
/* comp2.st.css */
:import {
  -st-from: './comp1.st.css';
  -st-default: Comp1;
}

.root {}
.partA {
  -st-extends: Comp1;

}
.partB {
  -st-state: someState;
}
.modifier {}
```

```css
/* app.st.css */
:import {
  -st-from: './comp2.st.css';
  -st-default: Comp2;
}

/* now without the explicit named import to .modifier */
Comp2::partA ::-stContext(Comp2)::modifier {} 
/* .comp2__root .comp2__partA .comp2__modifier */


/***  additional cases  ***/

/* not nested */
Comp2::partA::-stContext(Comp2)::modifier {} 
/* .comp2__root .comp2__partA.comp2__modifier */

/* nested pseudo-element */
Comp2::partA ::-stContext(Comp2::partA)::otherPart{} 
/* .comp2__root .comp2__partA .comp1__otherPart*/

/* with state */
Comp2::partA ::-stContext(Comp2::partB):someState ::-stContext(Comp2)::modifier {} 
/* .comp2__root .comp2__partA .comp2--someState .comp2__modifier */
```

### Notes
- Not settled on `::-stContext()`, open to suggestions (considered: `::-stUse`, `::-stScope`, `::-stInspect`, `::-stYield`)
- Providing completion for this feature from the LSP will require additional effort
- Our currently used selector parser does not provide good support for selectors nested within selectors (e.g. `.root::-stContext(.root::part)`)

**Comment by tomrav** [comment]
`::-StScope` feels off to me because `@st-scope` exists and serves a different function.

**Comment by tomrav** [comment]
Updated to include a case that's more reflective of real world usage.

**Comment by tomrav** [comment]
I've encountered another potential use for this feature.

At the moment, we do not provide the ability to import/export custom selectors from a stylesheet.
This could serve as a way to access custom selectors.

```css
/* base.st.css */
@custom-selector :--cs  .part > .x;
.part {}
.x {}
```

```css
/* index.st.css */
:import {
  -st-from: "./base.st.css";
  -st-default: Base;
}

.root ::-stContext(Base):--cs {}
/* .index__root .base__part > .base__x */
```

> We have recently added the ability to import `@keyframes` from stylesheets using a utility function inside the `st-named` declaration. The same approach should be used for importing `customSelectors(cs)` across stylesheets. See issue #1327

**Comment by nadav-ab** [comment]
seems a bit verbose

how about this solution?


```css
:import {
  -st-from: "./base.st.css";
  -st-default: Base;
}
.myClass.Base::part(.a) .myOtherClass .Base::part(.b){
 color:red;
}


```
