### ISSUE TITLE
Custom Pseudo-Class with Parameters

### ISSUE THREAD

**Issue by idoros** [wix/stylable#12]
```css
CustomTag:customState(val) {}
```
Transform to:
```css
.root CustomTag_root[data-CustomTag-customState="val"]
```

Usage example:
```css
.myForm::field:name(title):empty{
    background:blue;
}
```
