### ISSUE TITLE
JS Mixin with parenthesis but no arguments throws a warning

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1203]
When invoking a JS mixin with parenthesis but no arguments it fails and throws an error:  
`WARNING in Stylable: <PATH_TO_STYLESHEET>/app.st.css:19:5: myMixin(): argument at index 0 is empty`.

```js
/* mixin.js */
module.exports = {
  myMixin: function() {
    return {
      background: 'green',
      color: 'gold'
    };
  }
}
```

```css
/* app.st.css */
:import {
  -st-from: './mixin.js';
  -st-named: myMixin;
}

.target {
  -st-mixin: myMixin;   /* works */
  -st-mixin: myMixin(); /* fails */
}
```
