### ISSUE TITLE
mixin ignores mixed-in class type

### ISSUE THREAD

**Issue by idoros** [wix/stylable#121]
```css
@namespace "comp";
:import {
    -st-from: "./button.st.css";
    -st-default: Button;
}
.clicker {
    -st-extends: Button;
}
.clicker::label {
    color:red;
}
.myBtn {
    -st-mixin: clicker;
}
```
Will output:
```css
...
.comp--root .comp--myBtn::label { color:red; }
```
Should output:
```css
...
.comp--root .comp--myBtn.button--root .button--label { color:red; }
```
