### ISSUE TITLE
warning "unscoped class X will affect all elements" when merging themes

### ISSUE THREAD

**Issue by KutnerUri** [wix/stylable#1264]
In my project, I am attempting to have a system of _color_ and _accents_.
```tsx
//pseudo code
function App(){
  return (<div className="light-theme">
    <h1>header</h1>
    <Section>
        <div>good {getPartOfDay()}, {person.name}</div>
    {person.purchase && (
    </Section className="success-accent">
      <h2>Success!</h2>
      <div>
        you just bought {person.purchase}
      </div>
    </Section>
    ) }}
  </div>
}
```

Both `light-theme` and `success-accent` define css variables that will style html down the line.
When placed together, they will have a specific combination of colors:

```css
:import {
	-st-from: "../base/variables.st.css";
	-st-default: Variables
}

:import {
	-st-from: "../light-theme/light-theme.st.css";
	-st-default: Light;
};
:import{
	-st-from: "../win-accent/win-theme.st.css";
	-st-named: win;
};

.win .Light, .Light.win, .Light .win {
	-st-mixin: Variables(
		theme-name "'(light-win)'",
		theme-color #37b26c,
		theme-fg #57cc6d,
		theme-bg #d6fddd,
		theme-border-color #57cc6d,
	);
}
```

I got this error:
```
WARNING in Stylable: unscoped class "Light" will affect all elements of the same type in the document
WARNING in Stylable: unscoped class "win" will affect all elements of the same type in the document
```

Is there a way to ignore this error? like
```css
{/* @-st-expect-expand */}
.win .Light, .Light.win, .Light .win {
```

**Comment by barak007** [comment]
Hey 10x for opening an issue.
Currently there is no option to disable warnings, we will consider adding this feature. 
Also I'm trying to understand the requirement. Why do you need all the selector combinations?

There is a work around for this. using undocumented feature `-st-global`. you can use it until we figure out how to properly handle the issue.

```css
.theme-scope {
  -st-global: "*";
}
@st-scope .theme-scope {
  .win .Light, .Light.win, .Light .win {...}
}
```
