### ISSUE TITLE
Feature: support importing custom selectors across stylesheets

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1327]
We have recently added the ability to [import `@keyframes`](https://stylable.io/docs/references/keyframes) as named imports across stylesheets using a built-in utility function:
`-st-named: keyframes([KEYFRAME_1, KEYFRAME_2, ....])`

We should add the same functionality for `@custom-selectors`, allowing them to be imported and re-exported across stylesheets.

```css
/* base.st.css */
@custom-selector :--cs  .part > .x;
.part {}
.x {}
```

```css
/* index.st.css */
:import {
  -st-from: "./base.st.css";
  -st-named: customSelectors(cs);
}

.root :--cs {}
/* .index__root .base__part > button {} */ 
```
