### ISSUE TITLE
Document Mixin JS Mixins fallback behavior

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1349]
We need to add documentation for CSS-in-JS behavior under the Mixins section.

For example:
```js
module.exports = function() {
  return {
    color: ["red", "var(--main-color)"]
  }
}
```

When used, will return:
```css
.root {
  -st-mixin: myMixin;
}

/* output */
.root {
  color: red;
  color: var(--main-color);
}

```
