### ISSUE TITLE
Add ability to declare global custom properties pattern   

### ISSUE THREAD

**Issue by barak007** [wix/stylable#1357]
Right now in Stylable we have `@st-global-custom-property` directive to allow global custom properties.
But it's start to look bad when you have a lot of global custom properties.
This example taken form a real project (it takes 1/3 of the .st.css file).
```css
@st-global-custom-property
  --desktopVerticalMargin,
  --desktopHorizontalMargin,
  --desktopVerticalPadding,
  --desktopHorizontalPadding,
  --mobileVerticalMargin,
  --mobileHorizontalMargin,
  --mobileVerticalPadding,
  --mobileHorizontalPadding,
  --shd,
  --fnt,
  --txt,
  --alpha-txt,
  --bg,
  --alpha-bg,
  --brd,
  --alpha-brd,
  --rd,
  --txt_e,
  --alpha-text_e,
  --bg_e,
  --alpha-bg_e,
  --brd_e,
  --alpha-brd_e,
  --txt_h,
  --alpha-txt_h,
  --bg_h,
  --alpha-bg_h,
  --brd_h,
  --alpha-brd_h,
  --txt_s,
  --alpha-txt_s,
  --bg_s,
  --alpha-bg_s,
  --brd_s,
  --alpha-brd_s,
  --txt_d,
  --alpha-txt_d,
  --bg_d,
  --alpha-bg_d,
  --brd_d,
  --brw,
  --alpha-brd_d,
  --alignment,
  --direction;
```

To solve this we can add a simple pattern match functionality to the `@st-global-custom-property` or define a new directive like `@st-global-custom-property-pattern`

How it will be used:

```css
@st-global-custom-property --x, --y-*, --z-(*);

.root {
  color: var(--x); /* outputs var(--x) */
  color: var(--y-name); /* outputs var(--y-name) */
  color: var(--z-name); /* outputs var(--name) */
}
```
We can go crazy with the pattern matching but we can also allow one * or (*) if we want.

**Comment by idoros** [comment]
I assume global vars like that comes from 3d party dependencies. Do you have more examples of such cases? How many of them have a a common namespace that can be matched with a pattern?

**Comment by tomrav** [comment]
A similar sort of functionality can be achieved for now by using a simple formatter that returns an unscoped CSS variable usage.

```js
module.exports = {
  gVar: function(name) { return `var(--${name})`; }
}
```

```css
:import {
  -st-from: './formatter';
  -st-named: gVar;
}

.root {
  color: gVar(highlight); /* will result in "var(--highlight)" */
}
```
