### ISSUE TITLE
import/export of *.st.css in a nice way

### ISSUE THREAD

**Issue by DeDuckProject** [wix/stylable#144]
When I import a theme from `stylable-components` (for instance) I import its theme in my st.css file like so:

```css
:import {
    -st-theme: true;
    -st-from: "../node_modules/stylable-components/dist/src/style/default-theme/default.st.css";
}
```

a nicer way would be:

```css
:import {
    -st-theme: true;
    -st-from: "stylable-components/default.st.css";
}
```

@barak007
