### ISSUE TITLE
Allow destructuring imports to access a stylesheet's inner parts

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1484]
The Stylable CLI can generate either CJS or ESM output code for their appropriate environments.

One of the features that contributes to this is the ability to automatically generate an index file that contains references to every stylesheet root in the project.

Example:
```css
/* button.st.css */
:vars {
    bgColor: green;
}

.root {}
.icon {
    --textColor: green;
}
.label {}

@keyframes blink {}
```

Generated index file
```css
/* index.st.css */
:import {
    -st-from: './button.st.css';
    -st-default: Button;
}

Button {}
```

For component root type consumption this is enough. However, if you're interested in parts (classes, CSS vars, st vars, and keyframes) defined within a specific project stylesheet then you're forced to target the component stylesheet by path explicitly, instead of using the generated index stylesheet.

```css
/* external consumer */
:import {
    -st-from: 'other-project/index.st.css';
    -st-named: Button; 
    /* the Button's classes ".icon" and ".label",
        the variables "bgColor" and "--textColor" and 
        the keyframe "blink" are not exposed through this index file 
     */
}

.myButton {
    -st-extends: Button;
}
```

This means that a consuming project would need to be familiar with the target output of a 3rd party project to consume its inner parts. Targeting `other-project/cjs/button.st.css` or `other-project/esm/button.st.css` would require knowing about both the part to the stylesheet (`cjs` or `esm` in this case) and the stylesheet name (`button.st.css`) explicitly.

## Suggested solution - allow imports to be destructured 
A possible solution would be to extend the current capabilities of import statements to support a behavior similar to [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment).

> We still need to consider which type of parenthesis would be the best syntax here, "()" or "[]", for now, all examples below use the "()" option

```css
:import {
    -st-from: 'other-project/index.st.css';
    -st-default: SomeName(
        Button as MyButton( /* alias functionality maintained */
            icon as myIcon, /* alias for a destructured part */
            label, 
            bgColor, 
            --textColor, 
            keyframes(blink),
            Label( /* Exposed component root */
                text
            )
        ), 
        Keyframes(keyframes(blink)), 
        /* an element named "Keyframes" showing the difference to our keyframes function above */
    );
    -st-named: Button(
        icon as myIcon, 
        label, 
        bgColor, 
        --textColor, 
        keyframes(blink)
    ); 
}
.myIcon { /* imported icon and variables usage */
    background: value(bgColor);
    color: var(--textColor);
} 
/* ... */
```

This solution means we negate the requirement of structural knowledge of 3rd-party projects. Any inner part required can be accessed through the component root exposed in the index stylesheet through destructuring.

Furthermore, by allowing such imports, we can avoid having to use a `Member variable` type syntax, which can get bloated/repetitive in CSS-like syntax.

### A possible downside
Now that one can jump across stylesheets within a single import leads to the fact that any part of any stylesheet effectively becomes a public interface (when using the CLI to auto-generate the index).

To help combat this behavior another new feature is suggested in separate issue (will be linked once written...) to allow defining a stylesheet's export explicitly.
