### ISSUE TITLE
@keyframes should not scope the root

### ISSUE THREAD

**Issue by talh78** [wix/stylable#149]
When writing this in a Stylable stylesheet:
```css
@keyframes wheel-rotate-semi {
    0% { transform: rotate(180deg); }
    45% { transform: rotate(198deg); }
    55% { transform: rotate(234deg); }
    100% { transform: rotate(540deg); }
}
```

Output CSS is written with root scoping:
```css
@keyframes Loader3286110863💠wheel-rotate-semi {
    .Loader3286110863💠root 0% { transform: rotate(180deg); }
    .Loader3286110863💠root 45% { transform: rotate(198deg); }
    .Loader3286110863💠root 55% { transform: rotate(234deg); }
    .Loader3286110863💠root 100% { transform: rotate(540deg); }
}
```

When it shouldn't
