### ISSUE TITLE
Undefined variables has bad error messages

### ISSUE THREAD

**Issue by tyv** [wix/stylable#163]
```css
selecor {
    width: value(undefinedVar);
}
```

now reports:

```sh
ERROR in Cannot read property 'rule' of undefined
```

it could be improved with adding smth like
```ts
if (importIndex < 0) {
    //report error with `name` and `meta.source` source strings
}
```
after this line https://github.com/wix/stylable/blob/master/src/stylable-transformer.ts#L279
