### ISSUE TITLE
CSS custom property "import as" missing diagnostic

### ISSUE THREAD

**Issue by idoros** [wix/stylable#1689]
When importing a custom property and assigning a local name to it, it must start with `--` prefix.

 example:
```css
:import {
    -st-from: './button.st.css';
    -st-default: Button;
    -st-named: --bg as btnBg; /*should error/warn here*/
}
```
[playground reproduction](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%286%21%21import75from1%2522.A%2522%253B5default95named1--bg%2520as%2520btnBgC4.okB375extends90%252F*%2520background1var%257BbtnBg%257D%253B%2520*%252F4%294%27%7EA%21%27.root70--bg1greenC%27%29%7Eselected%216%27%2904881%253A%25202.st.css3utton4%255Cn50-st-6%27%252Findex27%2520%288%2520%252091B3%253BA%252Fb32C%253B4%29%2501CA9876543210_)
