### ISSUE TITLE
Inline compose exports

### ISSUE THREAD

**Issue by barak007** [wix/stylable#1740]
Assume we want to bring back `-st-compose`

One known limitation of composing classes is that you cannot use it in customizations targeting the component.
This following example is invalid and will not work because the `flex-center` class will not be added to the component exports

**comp.st.css**
```css
.root {}
.part {}
```
**theme.st.css**
```css
@st-import Comp from "./comp.st.css";

.flex-center {...}

Comp {
  -st-compose: flex-center; /* INVALID */
}

Comp::part {
  -st-compose: flex-center; /* INVALID */
}
```

We can introduce a new `-st-compose` behavior that will have the following:
1. throw an error if the origin component is not included in the build process (*)
2. throw if used in a non Stylable compound selectors 
3. will inject the class at the component JavaScript exports  

This will extends theme capabilities and decrease size of the css since this behavior can only be achieved with mixins.

(*) We might be able to create a "monkey patched" approach to solve it even if the component is not included in build but there are considerations of dynamic loading the composing module and identifying the component origin css.
