### ISSUE TITLE
@supports is not supported when used inside css mixin stylesheet

### ISSUE THREAD

**Issue by mykas** [wix/stylable#1810]
Example mixin:
```css
:vars {
  gap: 0;
}

/* Detect if the browser is safari */
@supports not (appearance: auto) {
  .root {
    gap: 0;
    margin: calc(value(gap) / -2) calc(value(gap) / -2);
  }
  .root > * {
    margin: calc(value(gap) / 2) calc(value(gap) / 2);
  }
}

.root {
  gap: value(gap);
}
```

Usage:
```css
:import {
     -st-from:"./mixin.st.css",
     -st-default: Gap;
 }
 
.root {
   -st-mixin: Gap(12px);
}
```

Output in Safari 12,13,14:
```css
.root {
   gap: 12px;
}
```

Expected in Safari 12,13,14:
```css
 .root {
    gap: 0;
    margin: calc(value(gap) / -2) calc(value(gap) / -2);
  }
  .root > * {
    margin: calc(value(gap) / 2) calc(value(gap) / 2);
  }
```
 
 
 cc @egidijusja
