### ISSUE TITLE
Root fails to be resolved in JS mixin containing an at-rule

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1811]
Failing test case:
```js
// mix.js
module.exports.gap = ([gap]) => ({
  '@media xxx': {
    '&': {
      gap: 0,
    }
  }
});
```

```css
/* a.st.css */
@st-import [gap] from './mix.js';

.codeMixedIn {
    -st-mixin: gap(12px);
}
```

Expected:
```css
.a__codeMixedIn {}

@media xxxx {
    .a__codeMixedIn { 
        gap: 0; 
        margin: calc(12px / -2) calc(12px / -2);;
    }
}
```

Actual:
```css
.b__codeMixedIn { 
}

@media xxxx {
    & {
        gap: 0;
        margin: calc(12px / -2) calc(12px / -2);
    }
}
```
