### ISSUE TITLE
custom-selector .root:state is transformed as 2 nested elements

### ISSUE THREAD

**Issue by idoros** [wix/stylable#186]
```css
.root {
    -st-states: unHighlight;
}

@custom-selector :--highlight .root:unHighlight :global(.highlight);

/* selector */
.root::highlight

/* will output (describe the unHighlight state as nested element) */
.app__root .app--unHighlight .highlight {}

/* should output */
.app__root.app--unHighlight .highlight {}
```

**Comment by tomrav** [comment]
This still happens, even with class name based states.

```css
.root {
    -st-states: unHighlight;
}

@custom-selector :--highlight .root:unHighlight :global(.highlight);

/* selector */
.root::highlight {}

/* output */
.x__root .x--unHighlight .highlight {}
```
