### ISSUE TITLE
Change dependency (asset) in `.st.css`  does not trigger build in  `stc` CLI watch mode

### ISSUE THREAD

**Issue by tzachbon** [wix/stylable#1923]
Changing an asset file used inside the `st.css` file does not trigger build in `stc` CLI watch mode.

Example:
`index.st.css`:
```css
.root {
	background: url('./icon.svg')
}
```

When I change the `icon.svg` file, it does not trigger a build when using it with `@stylable/cli` watch mode.

CLI version:
```
"@stylable/cli": "^4.3.3"
```
