### ISSUE TITLE
JS mixin error diagnostic is not clear

### ISSUE THREAD

**Issue by tzachbon** [wix/stylable#1953]
### What happened?

When I added an invalid value inside the js mixin declaration, the error diagnostic was unclear and pointed to something unrelated.

### Version

4.5.0

### Relevant log output

```shell
ERROR in /Users/src/app.st.css
/Users/src/app.st.css:11:23: Missed semicolon
```

> Note that the line it points to is not related to the place that the mixin was imported or used.
```


### Additional Context

`mixin.js`:
```js
module.exports = () => {
  return {
    'background-color': 'background: red'
  }
}
```
> The value is `background: red`, which is invalid

`app.st.css`:
```css
@st-import Mixin from "./mixin.js";

:global(html) {
    -st-mixin: Mixin;
}
```
