### ISSUE TITLE
inner part that extends root does not create a single compoundSelector 

### ISSUE THREAD

**Issue by barak007** [wix/stylable#1960]
### Actual Behavior

the class is nested.

https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%282%21%27*%2540st-import%2520Btn%2520from%2520%255C%27.3%255C%275**.x41Btn6*.x%253A%253A76**%27%7E3%21%27*.7*%2520%2520%2520%25201root56%27%29%7Eselected%212%276%255Cn0.st.css1-st-extends%253A%25202%27%252Findex03%252Fbutton04%2520%285%253B*6%29*7big4%250176543210*_

### Expected Behavior

should be placed in the same compoundSelector / chunk

### Version

@stylable/core@4.5.0

**Comment by tomrav** [comment]
playground link not working

**Comment by idoros** [comment]
can also be reproduced in a single stylesheet:
```css
.x {-st-extends: root}
.y {-st-extends: root}

.x::y {}
/*
transformed into: .index__x .index__y
should be       : .index__x.index__y
*/
```
