### ISSUE TITLE
Union Types

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1984]
- Multiple extends / compose - #946
- Improve custom selectors
- Support :is(), :where()
- Generics / templates - https://github.com/wix/stylable/issues/695

**Comment by barak007** [comment]
(WIP)

## Why?
* Enable stricter more aware completions 
* Enable multiple extends 
* Enable multiple composition of classes
* Enable support for utility libraries like `tailwind`

## When do we see it today?

```css
.x {-st-extends: CompA}
.y {-st-extends: CompB}
:is(.x,.y):?????
```

```jsx
function Comp({isVideo}){
    return isVideo ? <Video className={classes.root}/> : <Image className={classes.root}/>
}
```
