### ISSUE TITLE
Last chunk of selector list is not transformed in nested pseudo class selectors

### ISSUE THREAD

**Issue by tzachbon** [wix/stylable#2008]
### Actual Behavior

The last chunk of the selector list does not have the targeted selector context.

```css
.root { -st-states: a; }

.root:is(.x .y :a) {}
```

`:a` does not have the `.root` context.

[Playground link](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%28*%21%271%2520%280%2520%2520%2520%2520-st-states%253Aa%2520%253B0%291%253Ais%257B.x%2520.y%2520%253Aa%257D%2520%28%29%27%29%7Eselected%21*%27%29*%27%252Fbutton.st.css0%255Cn100.root%250110*_)

### Expected Behavior

```css
.root { -st-states: a; }

.root:is(.x .y :a) {}
```

`:a` will have the `.root` context since it is on the same level.

### Version

4.5.1

### Additional Context

It does work for a simple selector. [Playground link](https://stylable.io/docs/references/custom-selectors)

```css
.root {
    -st-states:a ;
}

.root:is(:a) {}
```
