### ISSUE TITLE
code formatting breaks when encountering a "\"

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#2035]
### Actual Behavior

This happens primarily with a `\` inside any rule, causing a weird duplication, over and over.

Before formatting:
```css
.root {
    color: red;\
    background: gold;
}
```

After formatting:
```css
.root {
    color: red;
    \
 background: gold;background
    background
}
```

After another formatting (and so it repeats):
```css
.root {
    color: red;
    \
 background: gold;background
    backgroundbackground background
}
```

### Expected Behavior

should not break source files.

### Version

4.6.0
