### ISSUE TITLE
Global CSS var declaration overrides import with no warnings

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#2160]
### Actual Behavior
CSS variable is kept global, and no warning is emitted.

This behavior also happens with `@st-custom-global-property`.

### Source
```css
@st-import [--bg] from './ns.st.css';
@property st-global(--bg);

.x {
    --bg: red;
}
```

### Output
```css
.ns__x {
    --bg: red;
}
```

### Expected Behavior

```css
.ns__x {
    --ns-bg: red;
}
```
Should emit a warning about declaration collision.

### Version

`@stylable/core@4.8.0` (latest)
