### ISSUE TITLE
Stylesheet not included when only "@property" is used

### ISSUE THREAD

**Issue by tzachbon** [wix/stylable#2171]
### Actual Behavior

In the webpack plugin when you have a CSS file that is directly imported in the JS and it imports a css-var which is defined by `@property`, the imported file is not considered "has side effects", does not get included and can lead to unexpected behaviors.

Take the following example:
```css
@st-import [--color] from './foo.st.css'

.root {
  color: var(--color);
}
```

```css
/* foo.st.css
*  This file won't get included since it was imported in CSS
*/

@property --color  {
    inherits: false;
    syntax: "<color>";
    initial-value: red;
}
```

As you can see if `foo.st.css` is not included and the initial value does not appear in the stylesheet, therefore `.root` will not have the color red.

### Expected Behavior

`@property` should be considered a side-effect and be included.

### Version

4.8.3

### Additional Context

This was recreated in the webpack plugin, and it should be recreated for anyone who uses [`hasImportedSideEffects`](https://github.com/wix/stylable/blob/3b2b62a92b2270d28e198464df413181dda2e21d/packages/build-tools/src/has-imported-side-effects.ts#L3)
