### ISSUE TITLE
Simplify extends / compose

### ISSUE THREAD

**Issue by idoros** [wix/stylable#218]
# Extends vs Compose

> Notice: this description is still WIP and not ready yet:  
> * consider themes
> * anything else?

Currently the way Stylable handles CSS class inheritance is not ideal and awkward. The purpose of this thread is to explain the issues related to the current behavior and suggest alternatives.

## Current state

Stylable offers 2 class `inheritance` configuration, [-st-extends](https://stylable.io/docs/references/extend-stylesheet) and [-st-compose](https://stylable.io/docs/references/compose-css-class), they allow for different ways of modifing the CSS and JS output and the way custom pseudo elements and states are transformed. 

### -st-extends
Accept a **single** CSS class or stylesheet reference and might modify the CSS output, JS output and meta type (used for building the CSS and code intelligence).

```css
@namespace "a";
:import {
    -st-from: ".b.st.css";
    -st-default: B;
    -st-named: innerB;
}
.local {}

/* extending a local class */
.extend-local-class { -st-extends:local; }
/*
Generated selector: .a__root .a__extend-local-class.a__local
Classname mapping: { "extend-local-class":"a__extend-local-class a__local" }
Inferred type: <typeof .local>
*/


/*
extending local root, this is useful when defining component variants in the same file as the component
*/
.extend-local-root { -st-extends:root; }
/*
generated selector: .a__root.a__extend-local-root
Classname mapping: { "extend-local-root":"a__extend-local-root" }
Inferred type: <a.st.css>

*notice* root is not added in the JS output, as we assume it comes with the component.
*notice* in the CSS selector. we assume the node the class is applied to is the components, hence no space in the selector. ".a__root.a__extend-local-root" and not ".a__root .a__extend-local-root"

*/



/* extending imported class */
.extend-import-class { -st-extends:innerB; }
/*
generated selector: .a__root .a__extend-import-class.b__innerB
Classname mapping: { "extend-import-class":"a__extend-import-class b__innerB" }
Inferred type: <typeof .innerB>
*/


/* extending StyleSheet */
.extend-import-root { -st-extends:B; }
/*
generated selector: .a__root .a__extend-import-root.b__root
Classname mapping: { "extend-import-root":"a__extend-import-root" }
Inferred type: <b.st.css>
*/
```

### -st-compose
Accepts **multiple** CSS class or stylesheet references and modify just the **JS output**.

```css
@namespace "a";
:import {
    -st-from: ".b.st.css";
    -st-default: B;
    -st-named: innerB;
}
.local {}

/* compose local class */
.compose-local-class { -st-compose:local; }
/*
Generated selector: .a__root .a__compose-local-class
Classname mapping: { "compose-local-class":"a__compose-local-class a__local" }
Inferred type: No type inference from compose
*/



/* compose local root*/
.compose-local-root { -st-compose:root; }
/*
Generated selector: .a__root.a__compose-local-root
Classname mapping: { "compose-local-root":"a__compose-local-root a__root" }
Inferred type: No type inference from compose
*/


/* compose imported class */
.compose-import-class { -st-compose:innerB; }
/*
Generated selector: .a__root .a__compose-import-class
Classname mapping: { "compose-import-class":"a__compose-import-class b__innerB" }
Inferred type: No type inference from compose
*/

/* compose imported stylesheet*/
.compose-import-root { -st-compose:B; }
/*
Generated selector:  .a__root .a__compose-import-root
Classname mapping: { "compose-import-root":"a__compose-import-root b__root" }
Inferred type: No type inference from compose
*/
```

### -st-compose & -st-extends summarize

We can see that the main difference between `-st-extends` and `-st-compose`, is that extends **modify the type** and result selector of the CSS class, while compose just ties several CSS classes together on the DOM through JS mapping.

|action|value           |CSS  |JS  |TYPE
|------|----------------|-----|----|----
|extend |local-class    |+    |+   |+ (1) 
|extend |local-root     |+ (2)|-   |+
|extend |import-class   |+    |+   |+ (1)
|extend |import-root    |+    |-   |+
|compose|local-class    |-    |+   |- 
|compose|local-root     |-    |+   |-
|compose|import-class   |-    |+   |-
|compose|import-root    |-    |+   |-

1. type of extended class should be resolved from the possible extend chain (but currently seems to have issues)
2. inheriting from local root doesn't add anything to selector, but causes the class to be considered a root class and root scoping removes the nested selector space between root and extending class (look at the `.extend-local-root` example above)

## Why is this good? bad? and alternatives

* **good**: 
    * `-st-extends` accept a single definition, which limit it to a **single type inheritance** - easier for now
    * `-st-extends` make sure that classes that extend a component will only match when set on the element of the correct component. by modifying the CSS to contain the root class of the extended component, and not adding the class to the JS output, assuming that the component will add its own root.
* **bad**:
    * **different behavior** for classes and stylesheet root
    * **add specificity** to all extending classes
* **alternative**: unify both into `-st-extends`  
    * allow extends to accept multiple values
        * keep **single type extend** restriction - warn for multiple extend values with incompatible type (we can just warn and select the first type)
    * stop modifying CSS
        * better straight forward intuitive output
        * lower specificity
        * **loose "validation" behavior**  - class extending Gallery would work on any element set with the class.
