### ISSUE TITLE
code-formatter ruins grid template formatting

### ISSUE THREAD

**Issue by alisey** [wix/stylable#2218]
Start with the following code:

```css
.foo {
    grid-template:
        "icon  name name ."    16px
        ".     type .    ."    16px
        ".     desc desc desc" 20px
        / 16px 3fr  2fr  4fr;
}
```

In VSCode, press Cmd + P, Format Document, get the following sad result:
```css
.foo {
    grid-template:
        "icon  name name ."16px ".     type .    ."16px ".     desc desc desc"20px / 16px 3fr 2fr 4fr;
}
```

We could just switch to Prettier if it supported Stylable, but unfortunately it doesn't.
