### ISSUE TITLE
build process for stylable-components

### ISSUE THREAD

**Issue by arnonkehat** [wix/stylable#223]
build process for stylable-components - put themes in a place in the project where they can be accessed easily

Today:

```css
:import {
  -st-from: "../../node_modules/stylable-components/dist/src/themes/wix/theme.st.css";
}
```

Should be:

```css
:import {
  -st-from: "stylable-components/wix"; 
}
```
