### ISSUE TITLE
theme should expose components like an index file

### ISSUE THREAD

**Issue by arnonkehat** [wix/stylable#224]
export stylesheets of all components should be imported with their default names. theme should expose button, like an index file.

today:

```css
:import {
  -st-from: "../../node_modules/stylable-components/dist/src/components/date-picker/date-picker.st.css";
  -st-default: DatePicker;
}
```

should be:

```css
:import {
  -st-from: "stylable-components/wix";
  -st-named: DatePicker;
}
```
