### ISSUE TITLE
functions with named parameters

### ISSUE THREAD

**Issue by idoros** [wix/stylable#231]
Currently Stylable supports JS mixins with argument list and this is fine for small functions with no optional params, but when using functions or CSS mixins with several params and no specific order it would be nice to pass just the mandatory/overridden params.

I couldn't find any CSS syntax / future spec that offer such input (@brucelawson asked in the [Houdini project](https://github.com/w3c/css-houdini-drafts/issues/551) and currently there is no answer there).

I think it should be something like this:

```css
.root {
    -st-mixin:
        modifyFunc(
            color1: green,
            color2: red
        );
}
``` 
 
This works nicely with `postcss` and `postcss-value-parser`, and I couldn't find any objection to the syntax in the CSS spec, however, any IDE that I tried it in raised an error on the colon between the param name and value.

We could support named params with the first space as separator between name and value:

```css
.root {
    -st-mixin:
        modifyFunc(
            color1 green,
            color2 red
        );
}
``` 

@nadavov, @barak007  - What do you think?
