### ISSUE TITLE
Undefined mixin throws exception

### ISSUE THREAD

**Issue by talh78** [wix/stylable#242]
Using stylesheet:
```css
.a {
    -st-mixin: Existing(1, 2, 3), Mixins;
}
```

causes an exception to be thrown when an undefined type is accessed [here](https://github.com/wix/stylable/blob/b3995d7b77be591c7ccfac73ce1eb7321e0260f6/src/stylable-value-parsers.ts#L228).

Should fail gracefully, and alert by diagnostics.
