### ISSUE TITLE
CSS vars support

### ISSUE THREAD

**Issue by idoros** [wix/stylable#247]
Because CSS vars are not namespaced by design, it would be nice to have some way to distinguish between conflicting and shared vars. Stylable can offer support for auto namespaced CSS vars, but it means the code needs to import vars in order to use them:

```css
:import {
    -st-from: "./panel-with-dropdown.st.css";
    -st-default: Panel;
}
:import {
    -st-from: "./dropdown.st.css";
    -st-named: --optionColor;
}
.panel {
    -st-extends: Panel;
    --optionColor: blue; // namespaced according to dropdown scope
}
```
