### ISSUE TITLE
When trying to resolve a non-existent symbol resolver returns _kind='css' and symbol is undefined

### ISSUE THREAD

**Issue by tempit** [wix/stylable#258]
```css
:import{
    -st-from: "./import.st.css";
    -st-named: shlomo;
}
```

In this case, import.st.css has no shlomo. When calling resolver.resolve for shlomo, we get a result with _kind='css', but symbol is undefined. 

Buggy code is at: https://github.com/wix/stylable/blob/e6d61bce8e59bb5bee7f88a6d0db8e59a1027449/src/stylable-resolver.ts#L63

Should check if symbol exists, and set _kind to 'invalid' or 'unknown' otherwise.
