### ISSUE TITLE
proposal: Mapped states parameters

### ISSUE THREAD

**Issue by idoros** [wix/stylable#2675]
## Current state

Stylable `-st-states` defines custom `pseudo-states` that can be targeted by a computed `CSS class`. Most built-in states types (except `boolean`) can accept a single parameter:

```css
.root {
    -st-states: text(string), 
                index(number),
                either(enum(this, that));
}

.root:text(abc) {}    /* .NS__root.NS---text-3-abc */
.root:index(5) {}     /* .NS__root.NS---index-1-5 */
.root:either(that) {} /* .NS__root.NS---either-4-that */
```

In addition there is an escape hatch to create an interface for states that are defined and activated **without Stylable**. This can be accomplished through [mapped states](https://stylable.io/docs/references/pseudo-classes#map-to-selector) that accept a global selector and transform the class part to represent a style interface that is not the default state computed class.

Currently mapped states do not take parameters and are "simply" replaced with a static selector, like a `boolean` state that can either be on or off:

```css
.root {
    -st-states: x('[data-x]');
}

/* x is off */
.root {}   /* .NS__root */

/* x is on */
.root:x {} /* .NS__root[data-x] */
```

## Goals

- Provide a way to represent more non Stylable state selectors with `mapped parameters` definition
- Support all parameter types (string, number, enum)
- Support a single parameter with room for a future syntax with multi parameters

## Proposal

- Optional mapping template string as the last (second) argument to all parameterized types - `state-name(param-type, selector-template?)`
- Use `$0` in the mapped string template to represent the parameter insertion - `'[attr="$0"]'`
    - Multi param states could potentially be added with `$1`, `$2`, etc. (with multiple parameters types as the initial arguments, pushing the mapped selector to the last argument)
- Limit the result selector to a compound selector for now, we can ease this restriction once we have better support for complex and multi-selector transformation and type analysis
- Mapped states are not available on the runtime API - activating them requires custom user code

### Examples

**map to multiple attributes**
```css
.root {
    -st-states: size(enum(small, medium, big), '[data-$0]');
}

.root:size(small) {}  /* NS__root[data-small] */
.root:size(big) {}    /* NS__root[data-big] */

.root:value(giant) {} /* invalid: invalid option */
```

**attribute value with ranged number**
```css
.root {
    -st-states: value(number(min(0), max(100)), '[value="$0"]');
}

.root:value(50) {}    /* NS__root[value="50"] */

.root:value(-1) {}    /* invalid: minimum 0 */
.root:value(101) {}   /* invalid: maximum 100 */
```

**mapped states not available in runtime**
```js
import { cssStates } from `./x.st.css`;

// unknown to the runtime
cssStates({size: 'big'}); // .x---size-2-big
cssStates({value: 50});   // .x---value-2-50
```
