### ISSUE TITLE
pseudo class multiple named parameters

### ISSUE THREAD

**Issue by idoros** [wix/stylable#269]
[pseudo classes with parameters](https://github.com/wix/stylable/pull/209) allows for defining custom pseudo classes that accept a **single** typed parameter:

```css
.root {
    -st-states: size( enum(small, medium, large) ),
                fieldName( string("^user-", maxLength(10) ) );
}
.root:size(medium):fieldName(user-name) {}
```

While a single parameter is good for most cases, it would be nice to be able to define selectors that can accept multiple optional arguments:

```css
/* possibly syntax */
date:-st-states("$year-$month-$day") {
	day:	number( min(1), max(31) ) 1;
	month: 	number( min(1), max(12) ) 1;
	year: 	number( min(1900) ) 1980;
}

.root {
    -st-states: start( date );
}

.root:start(day 15, month 2, year 1973) {}
.root:start {
    /* all args have defaults - equal to :start(day 1, month 1, year 1980)  */
}
```

This syntax shows 2 new ideas:
- complex custom state type that can accept multiple optional parameters
- custom state definition (outside of `-st-states`) that can possibly be exported and reused
