### ISSUE TITLE
Custom pseudo state string prefixes

### ISSUE THREAD

**Issue by idoros** [wix/stylable#271]
I think that in most cases Stylable should offer semantic API that helps to define a clearer style API. So in general I prefer having semantic types like `tags`, `enum`, `nth-child` or `lang` for custom pseudo-state. params that are defined by the API, transformed into low level CSS implementation, and are not dictated by the targeting selector (that simply pass a query argument).

for example:

```css
.root {
    /* define the cart custom state */
    -st-states: cart( tag )
}

.root:cart(shirt) {
    /* transforms into (search "shirt" in a value of whitespace-separated list of words):
        [data-cart~="shirt"]
    */
}
```

However we are offering lower level generic types like `string` and `number` that can be used to define the type of a pseudo-class param. And we might want to offer a way to use low level native abilities for `string` type that corresponds to CSS [attribute selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors).

String type could accept special prefixes that allow for custom matching of the state string value:

```css
.root {
    /* define the selected custom state 
    with a string parameter type */
    -st-states: selected( string );
}

.root:selected(username) {
    /* target an element with a state value that 
    is exactly the string argument "username" */
}

.root:selected(~user) {
    /* targets an element with a state value that
    is a whitespace-separated list of words, 
    one of which is exactly the string argument */
}

.root:selected(^user) {
    /* targets an element with a state value that
    is prefixed (preceded) by the string argument */
}

.root:selected($user) {
    /* targets an element with a state value that
    is suffix (followed) by the string argument */
}

.root:selected(*user) {
    /* targets an element with a state value that 
    contains at least one occurrence of the string argument */
}

.root:selected(|user) {
    /* targets an element with a state value that
    can be exactly the string argument or 
    can begin with the string argument immediately followed by a hyphen, "-" */
}
```
