### ISSUE TITLE
Invalid @keyframes from mixins

### ISSUE THREAD

**Issue by idoros** [wix/stylable#286]
When adding `@keyframes` through JS mixin, the transform outputs invalid keyframes definition, due to unnecessary name-spacing of animation keyframes list.

JS mixin:
```js
module.exports.addAnimation = function() {
    return {
        '@keyframes animName': {
             '0%': {'color':'black'}, 
             '100%': {'color':'red'}
        }
    };
}
```

Apply mixin in stylesheet:
```css
:import {
    -st-from: "./anim-mix";
    -st-named: addAnimation;
}
.x {
    -st-mixin: addAnimation;
}
```

Will output:
```css
@keyframes comp__animName {
    comp__0% { color: black; }
    comp__100% { color: red; }
}
```
