### ISSUE TITLE
Style API: rule interface

### ISSUE THREAD

**Issue by idoros** [wix/stylable#293]
There is an open [discussion](https://github.com/wix/stylable/issues/221) around how to keep semantic versioning of styles. 

## Known issues

I would like to address some of the raised issues with component style versioning:

* CSS's cascading nature automatically makes many properties public by context
* Component root  
    * a component is expected to be positioned from the outside (not within the component stylesheet)
    * layout might break if overridden from the outside of the component, like modifying `display: flex`
* component pseudo-elements (internal parts) might break if layed-out/positioned from the outside
* specificity changes, CSS order and structure rearrangement might modify the way a component is styled

## Possible solutions?

There are several ideas that could help reduce the amount of breaking changes by limiting the style API:

* reset component root with  `reset:all` and `display:relative`
* transform component root layouting, for example, if a Gallery stylesheet has `.root {display:flex}` we might want to transform any `Gallery { display: inline; }` to `Gallery { display: inline-flex; }`
* restrict declarations: 
    * prevent stylesheet root positioning: `.root { left: 20px; position: fixed; }`
    * prevent pseudo-elements positioning / layouting. assuming internal DOM positioning is managed by the component stylesheet.

While those limitations and defaults might help prevent some of the breaking changes scenarios, they don't solve all the known issues and add restrictions that are not always helpful.

I don't think we have enough real world use cases in order to fully comprehend the problem or even have all the necessary native APIs to decide on an holistic solution. 

I suggest starting with some tools that provides stylesheet authors more control over the style API:

## Style rule interface

Limit any direct CSS override with the `-st-filter` directive in order to guide the component consumers on how to style correctly and leave some intentional flexibility to the component author. 

`-st-filter` accepts a filter function that filters out and warns on every "private" declaration override.  

2 system filters functions are available as values: `allow()` and `deny()`. Both functions accept a list of CSS property values. A shorthand value is considered as the group of all of its longhand properties.

```CSS
/* gallery.st.css */
.root {
    /* prevent CSS override of overflow from the outside */
    -st-filter: deny(overflow);
    /* no restrictions within the stylesheet */
    overflow: hidden;
}
.navBtn {
    /* allow only background/border CSS override from the outside */
    -st-filter: allow(background, border);
    /* no restrictions within the stylesheet */
    border: 1px solid yellow;
}
```

```css
/* page.st.css */
:import {
    -st-from: './gallery.st.css';
    -st-default: Gallery;
}
Gallery {
    /* warning: will remove both declarations at build */
    overflow: visible; 
    overflow-x: visible; 

    /* anything else is */
    color: green
}
Gallery::navBtn {
    /* warning: will remove both declarations at build */
    font: 16px system-ui; 
    color: purple; 

    /* background & border are allowed */
    background: radial-gradient(salmon, rgba(255, 216, 0, 0.5));
    background-color: green;
    border-left: 2px solid red;
}
```

> Note: `-st-filter` doesn't restrict styling withing the defining stylesheet.

We can **avoid** dealing with override of `-st-filter` for the moment (might "narrow" the filter), by allowing a single filter definition in an inheritence chain. That means that a stylesheet that extends a Button stylesheet, with a certin filter, can't modify the filter. In case the Button component did't set a filter, then the extending stylesheet would be able to set the filter for any direct style override.

### Archetypes

Idealy styleasheet authors would not deal with `-st-filter` directly. A set of common `archtypes`, which are simply a collection of available definitions, can be extended in order to help define the stylesheet API.

```CSS
/* button.st.css */
:import {
    -st-from: './archetypes.st.css';
    -st-named: box, text;
}
.root {
    /* prevent CSS override of overflow from the outside */
    -st-extends: box;
}
.label {
    /* allow only background/border CSS override from the outside */
    -st-extends: text;
}
```

**Comment by idoros** [comment]
I have no particular attachment to `filter`, I'm not sure `override` is good, but lets ask around and see what works

**Comment by brucelawson** [comment]
A vote for my original suggestion (similar to the familiar !important
syntax):

display: flex !protected (restricted? fixed? private?)

https://twitter.com/fvsch/status/976394750126428160

**Comment by idoros** [comment]
@brucelawson - 2 questions:

**Verbosity**
`prop: value !accessor` is very verbose, it requires the stylesheet / archetype author to write every property / shorthand separably with a real value.

Do you think we should accept an `accessor` without a value?
```css
.root {
    padding: !private;
}
```

**Extensibility**
The reason I suggested a function-like syntax, like `allow()`, was to provide a future way for users to add their own custom filter functions. 

What do you say about (far future):
```css
:import {
    -st-from: '.my-filters';
    -st-named: custom-filter, simple-bg;
}
.root {
    /* limit any declaration according to custom-filter */
    all: !custom-filter(arg1, arg2);
    /* set limit on background abilities / values  */
    background: white !simple-bg(allowOneLayer, checkContrast);
}
```

In which case our custom  filter function will accept:
* the declarations it applies to (all, shorthand, longhands...)
* any additional arguments
* the context in which a declaration is being set
* value of declaration

And then can I chain them? `background: white !protected !simple-bg;`
