### ISSUE TITLE
Support private classes

### ISSUE THREAD

**Issue by idoros** [wix/stylable#294]
Currently any CSS class declared in a Stylable stylesheet is considered a `pseudo-element` public API. In some cases a stylesheet author could keep "template" classes by importing them and mixin them in, or use the future [`-st-filter: deny(*)`](https://github.com/wix/stylable/issues/293) to block any CSS overrides, but it would be much more helpful to introduce an `-st-access: private` directive that will simply hide the class from external overrides.

```css
/* gallery.st.css */
.navBtn {}
.internalBox {
    -st-access: private;
}
```

```css
/* page.st.css */
:import {
    -st-from: './gallery.st.css';
    -st-default: Gallery;
}

Gallery::navBtn {/* style the internal navBtn */}
Gallery::internalBox {/* error: unknown pseudo-element "::internalBox" */}
```

------
edit: possible values should be:
- public (default)
- private - cannot be accessed as a pseudo element or extended
- protected - cannot be accessed as a pseudo element, but can be styled in the context of a root that directly extends the stylesheet (or extending a stylesheet that extends the original stylesheet).
