### ISSUE TITLE
Export whole theme as single variable 

### ISSUE THREAD

**Issue by wtfil** [wix/stylable#3]
Exporting of multiple variables from theme is not that easy
Right now exporting of multiple variables looks like this
```css
:import(@theme) {                                                                                                                                                                                                                             
  -sb-named: inputBorder, borderRadiusInput, fontSizeSmall, lineHeightNormal, fontFamily, textMain, backgroundHover                                                                                                                           
} 
```

Using `*` or any other character for bulk export (like in es `import` statement) 
```css
:import(@theme) {                                                                                                                                                                                                                             
  -sb-theme: myTheme                                                                                                                          
} 
```
