### ISSUE TITLE
Wrong style generated when styling an inner-inner-element (v5.3.2)

### ISSUE THREAD

**Issue by DeDuckProject** [wix/stylable#302]
I have some Stylable components which extend one another as specified below

`a.st.css`:
```css
.root {}

.icon {}
```

`b.st.css`:
```css
:import {
    -st-from: "./a.st.css";
    -st-default: A;
}

.root {}

.a {
    -st-extends: A;
}

.a::icon {
    border: 2px dashed green;    /* this style is applied */
}
```

`c.st.css`:
```css
:import {
    -st-from: "./b.st.css";
    -st-default: B;
}

.root {}

.b {
    -st-extends: B;
}

.b::a {
    border: 2px dashed gold;     /* this style is applied */
}

.b::a::icon {
    border: 2px dashed red;      /* this style is NOT applied */
}
```

the problematic rule is the last one (`.b::a::icon`), which transpiles into this:
`.A4059733247--root .c1759243603--b.B1661361431--root .B1661361431--a .A--icon`
this part:`.A4059733247--root` at the beginning seems wrong. when I delete it from the CSS the style does get applied.
rolling back to stylable `5.3.0`. the traspiled rule looks like this:
`.c1759243603--b.B1661361431--root .B1661361431--a .A--icon` and works well.
