### ISSUE TITLE
`value()` eats last quote

### ISSUE THREAD

**Issue by dangreen** [wix/stylable#306]
```css
:vars {
	test:
		value1,
		value2,
		'value3';
}

:global(body) {
	test: value(test);
}
```
emits
```
body {
	test: value1,
		value2,
		'value3; /* <== */
}
```

**Comment by barak007** [comment]
Thanks for the report. this is a bug where the core issue is the way we strip quotes with regexp.
However as a work around you can wrap the entire expression in quotes 
Example: 
```css
:vars {
	test: "value1, value2, 'value3'";
}
```
