### ISSUE TITLE
Global state namespace

### ISSUE THREAD

**Issue by idoros** [wix/stylable#313]
At the moment, `*:state` selector is namespaced according to the stylesheet scope namespace:

```css
@namespace "ns";
.root { -st-states: a; }
.root *:a {} /* .ns__root   [data-ns-a] */
.root *:b {} /* warn: unknown pseudo-state "b" */
```

This behavior is by design. It creates a CSS selector that 
- targets internal parts (or nested instances) of the component
- in a specific state
- under the component HTML sub-tree.

I think that if we want to allow this, then the feature is not complete, because unique states on internal elements are not valid:

```css
@namespace "ns";
.internal-element { -st-states: a; } /* state is not defined on root */
.root *:a {} /* warn: unknown pseudo-state "a" */
```

- [ ] One of these should happen:
* pick up all the available states from all the internal elements
* check global state against native pseudo-classes only
   * optionally we could have internal elements "inherit" the root states and allow `:scope(:state)` selector, similar to `:global()`.

 - [ ] Documentation should be added
