### ISSUE TITLE
JS mixin on extended class

### ISSUE THREAD

**Issue by idoros** [wix/stylable#314]
[Currently](), `JS based mixins` are used as template engines for CSS fragments with no scope definition, and are transformed using the `root` of the "mixed-in" stylesheet instead of the selector scope they are "mixed-into":

```js
export const boldGallery = () => {
    return {
        '::btn': {
            'font-weight': 'bold'
        }
    }
}
```

```css
@namespace "gallery";
:import {
    -st-from: "./bold-gallery.js";
    -st-named: boldGallery;
}
.root { 
    -st-extends: Gallery;
    -st-mixin: boldGallery;
}
/* OUTPUT:
Assuming our gallery has a pseudo-element named button, 
the selector is transformed to target that button selector:

.gallery__root   .gallery__button.button__root { font-weight; bold; }
*/
```

When applying to an internal part, of another stylesheet, that extends our gallery:
```css
@namespace "page";
:import {
    -st-from: "./gallery.st.css";
    -st-named: Gallery;
}
:import {
    -st-from: "./bold-gallery.js";
    -st-named: boldGallery;
}
.gallery{ 
    -st-extends: Gallery;
    -st-mixin: boldGallery;
}
/* 
OUTPUT:
The sub-selector part appended by the mixin is transformed 
using the `root` of the "mixed-in" stylesheet.:

.page__gallery.gallery__root   .page__btn{ font-weight; bold; }

SHOULD BE:
.page__gallery.gallery__root   .gallery__btn{ font-weight; bold; }
*/
```

I assume that if the mixin specifically resolved with plain classes, like `{ '.btn': {} }`, then these selectors would be transformed using the "mixed-in" root scope. The previous example should transform to: `.page__btn` (assuming the page has a `.btn` class).
