### ISSUE TITLE
Mixin Scope

### ISSUE THREAD

**Issue by idoros** [wix/stylable#315]
## Mixin Transform

When Stylable transforms CSS, it needs to know on which `scope` this transformation occurs, in order to target the correct elements at run-time.

### Stylesheet

For instance in a stylesheet with the namespace `abc`, the class selector `.classA` will be transformed to `.abc--classA`:

```css
@namespace "abc";
.classA {} /* .abc__classA {} */
```

### CSS Fragment

When transforming a CSS fragment, the `scope` can potentially be taken from the "mixed-in" location or from the fragment source.

Stylable mixin can be applied from a [CSS definition](https://stylable.io/docs/references/mixins#css-mixins) or a [Javascript definition](https://stylable.io/docs/references/mixins#javascript-mixins) with different behaviors:

```css
@namespace "fromCSS";
.mix {}
.mix .inner-class {}
```

```js
export const mix = () => {
    return {
        '.inner-class': {}
    }
}
```

```css
@namespace "comp";
:import {
    -st-from: "./cssmix.st.css";
    -st-named: mix as css-mix;
}
.a { -st-mixin: css-mix; }
/* OUTPUT:
.comp__a {}
.comp__a .fromCSS__inner-class {}
*/

:import {
    -st-from: "./jsmix.js";
    -st-named: mix as js-mix;
}
.b { -st-mixin: js-mix; }
/* OUTPUT:
.comp__b {}
.comp__b .comp-inner-class {} - JS has no scope
*/
```

* `CSS based mixins` are used as templates for component, element and shared classes, so they are transformed to target the origin definition 
* `JS based mixins` are used as template engines for CSS fragments with no scope definition, and are transformed to the target the "mixed-in" definition

> currently there is a [bug](#314) that scopes the JS mixin just to the root of the "mixed-in" stylesheet 

## Scoped JS Mixin

Stylable could offer a way to build Javascript mixins that can indicate its `type` by referencing a CSS component or element. This type can be used to transform the css fragment to target the desired `type` and to validate its usage context.

```js
import ButtonStyle from './button.st.css';
export const reflectiveButton = () => {
    return {
        '@extends': ButtonStyle,
        'background': 'white',
        '::label': {
            'background': 'yellow'
        }
    }
}
```

```css
@namespace "comp";
:import {
    -st-from: "./button.st.css";
    -st-default: Button;
}
:import {
    -st-from: "./reflective-button.js";
    -st-named: refelectiveButton;
}
.myBtn { 
    -st-extends: Button;
    -st-mixin: refelectiveButton;
}
/* OUTPUT:
.comp__myBtn.button__root { background: white; }
.comp__myBtn.button__root .button__label { background: yellow; }
*/
.notABtn { 
    -st-mixin: refelectiveButton;
}
/* OUTPUT:
WARN: refelectiveButton mixin is applied on an element that is not of type "./button.st.css" 
.comp__myBtn { background: white; }
.comp__myBtn .button__label { background: yellow; }
*/
```

## Stuff ToDo
- [ ] add missing documentation about how this works
- [ ] discusss the scoped JS mixin idea (might talk about JS mixins type annotations at the same time...)
