### ISSUE TITLE
Exception when trying to mixin a named class import with a state

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#324]
Example case

```css
/* ./imported.st.css */
.myClass {
    -st-states: someState;
}
.myClass:someState {}


/* ./my-file.st.css */
:import {
    -st-from: "./imported.st.css";
    -st-named: myClass;
}

.root {
    -st-mixin: myClass;
    color: red;
}
```

Throws exception: `unknown pseudo-state "myClass"`

Specific steps to reproduce:
Note that while it has a state defined, I'm not attempting to use it in `my-file.st.css`, it does have to be used (even without declarations) in the `imported.st.css`. 

Also - the class using the mixin (`.root`) must have at least another declaration, in this case `color: red`.
