### ISSUE TITLE
Feature proposal: Inferred variable types

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#350]
> Note: this proposal used to exist as a PR that is now closed, re-opening as issue.

# Inferred Variable Types

Stylable can infer the following variable types from your variable declaration:

| Type | inferred by |
|----|----|
|color| recognized color name / color hexa format / rgba format | 
|cssUnit| number + recognized unit | 
|percentage| number+% | 
|image| base64 image / image url | 
|number| a number | 
|string| wrapped by quotation marks |

Native Enum types are inferred for their values in commonly used enums. 

* `lineStyle`
* `display`
* `bezierCurves`
* `positionKeywords`
* `repeatStyleKeywords`
* `lineStyleKeywords`
* `boxKeywords`
* `geometryBoxKeywords`
* `transitionTimingFunctions`

For example: `display` is the inferred Enum type for the `block` declaration value.

> Notes:
> Variable types default to string if no better match is found.
> 
> Stylable treats strings in much the same way as Typescript treats any, allowing string where any-type is expected, allowing any-type where string is expected

## Variable validation 
By using these types Stylable can provide you with better diagnostics while you're developing.

Wrapping any variable with quotation marks sets its type as `string`.
```css
    :vars{
        a: 5;       /* inferred as number       */
        b: "5";     /* inferred as string       */
        c: block;   /* inferred as display-enum */
        d: "block"; /* inferred as string       */
        e: 10px;    /* inferred as cssUnit      */
        f: "10px";  /* inferred as string       */
    }

    .myComp{
        font-weight: value(a) /* no warning as number is allowed for font-weight */
        font-weight: value(b) /* no warning as string is allowed everywhere */
                
        display: value(c);    /* no warning as display-enum is allowed for display */
        display: value(d);    /* no warning as string is allowed for everywhere */

        width: value(c)       /* warn display enum is not allowed in width */
        width: value(d)       /* no warning as string is allowed for everywhere */
        width: value(e);      /* no warning as cssUnit is allowed in width*/
        width: value(f);      /* no warning as string is allowed for everywhere */
        
        content: value(a)          /* no warning as content allows string, that means any type is allowed */
        border: solid 1px value(a) /* no warning as shorthand values are currently left out of scope */
    }
```

Variable types are also checked when overriding variables and passing variables to formatters/mixins.
