### ISSUE TITLE
Pseudo-class usage with quotes returns illegal selector

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#352]
Trying to use quotes in a pseudo-state selector parameter return illegal HTML result.

Example:
```css
.root {
    -st-states: blah(string);
}

.root:blah(asdasd)   {} /* works */
.root:blah("asdasd") {} /* bug   */
```

Generated CSS:
```css
.app3690410570--root {
    -st-states: blah(string);
}

.app3690410570--root[data-app3690410570-blah="asdasd"]   {} /* legal   */
.app3690410570--root[data-app3690410570-blah=""asdasd""] {} /* illegal */
```
