### ISSUE TITLE
[WIP] CSS-Blocks Comparison

### ISSUE THREAD

**Issue by idoros** [wix/stylable#359]
THIS DOCUMENT IS WORK IN PROGRESS
-----

Both projects provides a way to define a component based style system with the help of a preprocessor that uses static analysis to transform a CSS super-set into vanilla CSS, providing errors and warnings during authoring / build-time.

While both projects have lots of similarities, they were designed with different aspects in mind. [Stylable](http://stylable.io) aims for customization while [CSS-Blocks](http://css-blocks.com) goes for optimizations. That doesn't mean that Stylable is not optimized or that CSS-Blocks doesn't have customization features.

I believe the similarities of the projects are an encouraging sign. We both set to tackle similar issues, and building on top of ideas like [BEM](http://getbem.com/) and [CSS Modules](https://github.com/css-modules/css-modules), in a convulsion evolution way, we found similar solutions.

> Note: this is written from the perspective of `Stylable`. I haven't used `CSS-Blocks`, and I might be mistaken in some of my assumptions (hopefully I will be corrected by the CSS-Blocks team).

## Stylesheet source file

Both projects defines a component style using a CSS stylesheet file:

| Stylable         | CSS-Blocks       |
|------------------|------------------|
| `*.st.css`       | `*.block.css`    |

> Notice that although the primery use case for those stylesheets is to reflect a specific component, in both projects, `commons`, `interfaces` and other project level CSS can be defined in such stylesheet files. 

## Component top level element

In the component sub-tree, the top level element(s) can be targeted in a specific way:

| Stylable         | CSS-Blocks       |
|------------------|------------------|
| `.root` {}       | `:scope` {}      |

> In Stylable we also considered `:scope` or `:root` as the definition for the top element, and decided to go with `.root` in order to better represent the specificity and behavior of a class.

## Component inner element

Both projects use CSS classes to target a component inner elements and expose them as external API's for other stylesheets (see customizations).

| Stylable          | CSS-Blocks       |
|-------------------|------------------|
| `.element` {}     | `.element` {}    |

## Custom states

Both projects offers a way to declare and target custom states on any element of the component sub-tree.

**Stylable**

```css
/* defines custom states for any element in the component DOM */
.root { -st-states: name; }
.element { -st-states: name; }

/* target custom states */
.root:name {}
.element:name {}

/* define non boolean states */
.element {
    -st-states: size(enum(small, medium, big)),
                category(tag),
                product(string),
                amount(number);
}

/* target non boolean states */
.element:size(medium) {}
.element:category(pants, shirts) {}
.element:product(headphones):amount(5) {}
```

There are several features in the [planned](https://stylable.io/docs/references/state-parameter-types#future-intent) around state types.

> Stylable offers additional [validations for non boolean states](https://stylable.io/docs/references/state-parameter-types) and [custom state mapping](https://stylable.io/docs/references/pseudo-classes#mapped-states).

**CSS-Blocks**

```css
/* 
defines and targets a boolean or string value state on any element in the component DOM.
*/
:scope[state|name] {}
.class[state|name] {}
.class[state|name="value"] {}

/* future */

/* target any element with such state in the subtree */
[state|name] {}
```

## Dev name(space)

In order to achive better developer experience, both projects offers a way to declare a stylesheet name to be used as part of the namespacing (with fallback to filename and automatic conflict resolvement):

**Stylable**

```css
@namespace "my-comp";
```

**CSS-Blocks**

```css
:scope { block-name: my-comp; }
```

## Connect stylesheets together

To represent components or even project commons, we need the ability to connect definitions between stylesheets.

**Stylable**

```css
:import {
    -st-from: './other-comp.st.css';
    /* import the root element */
    -st-default: OtherComp;
    /* inner elements, vars and other symbols can be individualy imported */
    -st-named: inner-element, color1; 
}
```

**CSS-Blocks**

```css
/* reference the other block */
@block-reference other-block from "./block-1.block.css";
```

## Object-oriented features

Since our stylesheets reflects our components, we need to enable the same object oriented relations.

| Feature                   | Stylable            | CSS-Blocks       |
|---------------------------|---------------------|------------------|
| implements                |  -                  | +                |
| extends                   |  +                  | +                |
| inner-element level       |  +                  | -                |

**Stylable**

Component level inheritance:
```css
@namespace "super-btn";
:import {
    -st-from: './btn.st.css';
    -st-default: Btn;
}
/* component extends the "Btn" definition - inherits states and internal parts */
.root {
    -st-extends: Btn;
}
```

Inner element inheritance:
```css
@namespace "form";
:import {
    -st-from: './btn.st.css';
    -st-default: Btn;
}
/* internal element extends "Btn" definition just like to .root */
.submit {
    -st-extends: Btn;
}
```

> Look at how inheritance works with [states](https://stylable.io/docs/references/pseudo-classes#state-inheritance) and [elements](https://stylable.io/docs/references/pseudo-elements) in order to understand how an extended style API is overridden and extended. 

**CSS-Blocks**

Component level inheritance:
```css
@block-reference btn from "./btn.block.css";
:scope {
    block-name: super-btn;
    extends: btn;
}
```

Component level interface:
```css
@block-reference btn from "./btn.block.css";
:scope {
    block-name: super-btn;
    implements: btn;
}
/* stylesheet MUST contain the full implementation defined in the "Btn" reference */
```

## Customizations

We want to style extended style definitions. While Both projects allows for customizations, `Stylable` puts more emphasis on style API and offers access into deep parts of an imported definition. 

**Stylable**

Through inheritance:
```css
:import {
    -st-from: './gallery.st.css';
    -st-default: Gallery;
}
/* .root is a Gallery */
.root {
    -st-extends: Gallery;
}
/* deep selector API */
.root::navBtn::label {}
```

Through composition:
```css
:import {
    -st-from: './gallery.st.css';
    -st-named: navBtn;
}
/* style any navBtn label under the root */
.root .navBtn::label {}
``` 

**CSS-Blocks**

Through inheritance:
```css
@block-reference Gallery from "./gallery.block.css";
/* :scope is a Gallery */
:scope {
    extends: Gallery;
}
.navBtn {} /* ??? ToDo: check if this works */
```

Through composition (block paths):
```css
@block-reference Gallery from "./gallery.block.css";
/* style any navBtn under scope */
Gallery.navBtn {}
```

## User level constraints

Both project roadmap contains ways to restrict customization or inheritance:

* Stylable - [CSS Interface](https://github.com/wix/stylable/issues/293), [private classes](https://github.com/wix/stylable/issues/294)
* CSS-Blocks - Extension Constraints
 * [custom constraint and conflicts](https://github.com/linkedin/css-blocks/issues/51)

## Optimizations

**Stylable**

Stylable doesn't go as deep into reorgenaising the source code while transforming into vanilla CSS. Available optimizations are:

 * `removeUnusedComponents` - any style-rule that contains a reference to a component that does not exist in the bundle is removed
 * `shortNamespaces` - set the shortest possible namespace for stylesheets in the context of the build
 * `classNameOptimizations` - set the shortest possible class name in the context of the build
 * `removeStylableDirectives` - remove Stylable specific syntax (provide DX in non-production mode)
 * `removeComments` - remove source comments...
 * `minify` - remove any unnecessary characters and whitespace

 > Future:
 > * allow config to fully control name transformations to achieve a persistent target
 > * add state optimizations
 > * expose `clean-css` optimizer options

**CSS-Blocks**

> ToDo: get internet or Chris to help describe this... (I'm on a plane!) 

## CSS restrictions

In order for `CSS-blocks` to achieve a high level of optimization, it uses [OptiCSS](https://github.com/linkedin/opticss) to breakdown the source CSS, reorganize it and output an optimized CSS that keeps the original intent. This process needs a good understanding of the relations between style-rules and component DOM structure. And this restricts some of the natively available features.

> Notice that as `OptiCSS` matures, some of these restrictions might be improved!

| Feature             | Stylable            | CSS-Blocks       |
|---------------------|---------------------|------------------|
| !important          |  not recomanded     | -                |
| tag selector        | +                   | -                |
| attribute selector  | +                   | -                |
| Logical Combinators :matches(), :not(), :something() and :has() | + | - |
| Complex selectors   | +                   | [only one combinator in per selector](https://css-blocks.com/api/#1-only-one-combinator-per-selector-) |
| Multiple class names on DOM element  | (1)  | -                |

* (1) `Stylable` doesn't currently restrict the amount of CSS classes that can be set on a DOM element, however it is highly recomanded to apply 1 class per element (like `CSS-blocks`). This rule doesn't actually restrict an element to 1 class name, because CSS compositions on the CSS side may attach additional class names to the exported JS module mapping. 

-----

## Other points of interest

* specificity of source
* future CSS
  * web-components (`::part()` & `::theme()`)
  * CSS custom properties
  * custom selectors (set you own specificity!)
  * Houdini
* mixins / formatters
* build-time vars
* opt-out of scoping (`:global()` in Stylable) 
* runtime
* sourcemaps?
* integrations 
  * packagers
  * views / templates
  * IDEs
* dev tools
* test-kit

-----

## CSS-Blocks Questions:

1. difference between global state and state? wouldn't a normal state can be targeted using `Block Paths`?

```css
/* application.block.css */
@block-global [state|is-loading];
```

```css
/* navigation.block.css */
@block-reference app from "application.block.css";
app[state|is-loading] .logo {}
```
