### ISSUE TITLE
Root pseudo-element available when extending an internal class

### ISSUE THREAD

**Issue by tempit** [wix/stylable#383]
This should throw an error (bottom line in 2nd file) - pseudo-element 'two' should not exist on .local
```css
/* shared.st.css */
.one {}
.two {}
```
```css
:import {
    -st-from: "./shared.st.css";
    -st-named: one;
}
.local {
    -st-extends: one;
}
.local::two {} /* ::two shouldn't be a custom pseudo element */
```
