### ISSUE TITLE
Question: Is it possible to override Stylable states?

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable#389]
## The question
Meaning that a component A is defining states, and a consumer component B, which extends A's stylesheet, can apply a state through css only (without passing props to A that will apply the states).

## The Use-case
The use-case is for example, a `<Text/>` component defines a `skin` and `size` states (controlled by React props).

If I have this `<Text/>` component embedded in some other component B,
and B should be able to be styled from outside (
using css only), and let that styling have the ability to affect the `skin` and `size` of `<Text/>`.

**Comment by hepiyellow** [comment]
I see.
I would like to avoid `comp-b` having to render `<Text/>` with different React props (thus setting different state). I would like to achieve it only by css.
So the solution I see is to use mixins.

For example:
```css
/* text.st.css */
.root {
    -st-states: size(enum(small, large));
}
.sizeSmall {
  font-size: 16px; 
}
.sizeLarge {
  font-size: 24px;
}
.root:size(small) { 
   -st-mixin: sizeSmall;
}
.root:size(large) { 
   -st-mixin: sizeLarge;
 }
```
```css
/* comp-b.st.css */
:import {
    -st-from: './text.st.css';
    -st-default: Text, sizeSmall;
}
.label {
    -st-extends: Text;
    -st-mixin: sizeSmall
}
```

The JS of `comp-b` would look like:
```js
import style from './comp-b.st.css';
<comp-b>
  <Text {...style('label')}/>
</comp-b>
```
In this case whatever `<Text/>` renders as the default state of `size`,
it will be overridden by the `comp-b`'s mixin?

**Comment by idoros** [comment]
The pattern you showed here should work, the mixins themselves have nothing to do with the with the component state, they are simply used internally in the state and externally as a style, overriding the default  look.

However, it does go against the idea of Stylable that a component should be "styleless".

**Comment by hepiyellow** [comment]
### Styleless
Could explain: component should be "styleless"?

### Using state
I feel that using Stylable state for stuff like `size` as in the example above, might be the wrong approach, as a `<Text/>` component will not be changing it's `size` state during its lifetime. Unlike states like `focus`, `hover`, etc...
When using states for such "fixed" styling, we un-necessarily involve Javascript, where as css would be enough.
This mean that theme-ing becomes impossible with css only, except for using mixins.

#### Theming using css:
```js
/** MyForm component */
import style from './MyForm.st.css';
export class MyForm {
  render() {
    return (
      <div {...style('root', {}, this.props)}>
        <Text className={style.firstName}/>
        <Text className={style.lastName}/>
      </div>
  )
)
```

```css
/* MyForm.st.css */
:import {
    -st-from: './text.st.css';
    -st-default: Text, sizeSmall, sizeLarge;
}

.root {
}

.enlargeFirstNameTheme::firstName {
  -st-extends: Text;
  -st-mixin: sizeLarge
}
.enlargeFirstNameTheme::lastName {
  -st-extends: Text;
  -st-mixin: sizeSmall
}

.enlargeLastNameTheme::firstName {
  -st-extends: Text;
  -st-mixin: sizeSmall
}
.enlargeLastNameTheme::lastName {
  -st-extends: Text;
  -st-mixin: sizeLarge
}

```

```js
/* MyFormConsumer */
import myFormStyle from '../MyForm.st.css';
render = () => (
  <MyForm className={myFormStyle.enlargeLastNameTheme} />
)
```

#### Theming using state and props:
```js
/** MyForm component */
import style from './MyForm.st.css';
export class MyForm {
  render() {
    return (
      <div {...style('root', {}, this.props)}>
        <Text 
            text={this.props.firstName}
            size={this.props.theme === 'enlargeFirstNameTheme' ? 'large': 'small'}         
         />
        <Text 
            text={this.props.lastName}
            size={this.props.theme === 'enlargeLastNameTheme' ? 'large': 'small'}         
         />

      </div>
  )
)
```

```css
/* MyForm.st.css */
.root {
}
```

```js
/* MyFormConsumer */
import myFormStyle from '../MyForm.st.css';
render = () => (
  <MyForm theme="enlargeLastNameTheme" />
)
```
