### ISSUE TITLE
Adding the ability to composite animation @keyframes  when wrapped 

### ISSUE THREAD

**Issue by RashelleKosib** [wix/stylable#397]
I would like to have a support for Scoped Animations , just like we have in CSS modules.
Extending keyframes directly works, but not when you wrap it in another css module (like .bounce)

ScopedAnimations.css:
```css
.root {
  padding: 20px 10px;
}

.ball {
  composes: bounce from "shared/styles/animations.css";
  width: 40px;
  height: 40px;
  border-radius: 20px;
  background: rebeccapurple;
}
```
______________________

shared/styles/animations.css:
```css
@keyframes bounce {
  33% { transform: translateY(-20px); }
  66% { transform: translateY(0px); }
}

.bounce {
  animation: bounce 1s infinite ease-in-out;
}
```
