### ISSUE TITLE
Can’t use same name for mixin class if I have the same class name

### ISSUE THREAD

**Issue by lbelinsk** [wix/stylable#408]
```
:import {
 -st-from: "./button/button.st.css";
 -st-named: standard;
}

.root .standard { -st-mixin: standard}

```

I would expect either to get an error or even better to have this supported.

**Comment by mykas** [comment]
This issue makes code really messy if you want to put certain classes to files. Please prioritise this.

**Comment by tomrav** [comment]
Importing a named class and then using it, preserves the class namespace.
in your case `.root .standard` will transform to `.entry__root .button__standard`.

However, when mixing in the `standard` symbol, it actually refers to the local `.standard` class and reaches a circular dependency, preventing the mixin from being applied (see #428 for further details). 

While we're not entirely sure why'd you need the specific capability of mixing in an imported class unto itself, the following should work.

```css
:import {
 -st-from: "./button/button.st.css";
 -st-named: standard, standard as standardMix;
}

.root .standard { -st-mixin: standardMix; }
```
