### ISSUE TITLE
Scoping with theme scope renders incorrect stylesheet

### ISSUE THREAD

**Issue by mykas** [wix/stylable#424]
This is related with initiative to support theming on `wix-ui-core`.

Before I'll try to explain this issue I want you to understand that I don't know how this scoping thing works and only found a workaround that just works. 

The issue is  that when I try to scope my component class with theme scope: 
```css
@namespace "backoffice-button";

:import {
  -st-from: "../backoffice.st.css";
  -st-default: BackOffice;
}

:import {
  -st-from: "../../../components/button-next/button-next.st.css";
  -st-default: ButtonNext;
}

:import {
    -st-from: '../colors.st.css';
    -st-named: B10, F00, B20, D55,R10,R20,P10,P20, G10, G20,D80
}

.textButton {
  -st-extends: ButtonNext;
}
.iconButton {
  -st-extends: ButtonNext;
}


BackOffice ButtonNext {
  box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  text-align: center;
  border: 2px solid;
  
  outline: none;
  transition: all 100ms linear;

  height: 36px;
  border-radius: 18px;
  padding: 0 23px;

  background-color: value(B10);
  border-color: value(B10);
  color: value(D80);
}
```

this will render stylesheet and add it to the head in this order:
```css
.backoffice-button858907201--root .backoffice-theme2450484078--root .core-button2204479507--root {
  box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  text-align: center;
  border: 2px solid;
  
  outline: none;
  transition: all 100ms linear;

  height: 36px;
  border-radius: 18px;
  padding: 0 23px;

  background-color: #3899EC;
  border-color: #3899EC;
  color: #FFFFFF;
}
```
As you see we have back backoffice-button-root >  backoffice-theme--root >  core-button--root order. 

But my code gets rendered in this order:
```html
<div class="backoffice-theme2450484078--root">
   <button class="core-button2204479507--root backoffice-button858907201--small" type="button"> 
        small
  </button>
</div>
```
This results in classname mismatch and I can't seem to see the theme styles applied.

In `js` file I am importing theme and button css like this:
```jsx
import { ButtonNext } from "../../../src/components/button-next";
import { buttonnext, backOfficeTheme } from "../../../src/themes/backoffice";

<div className={backOfficeTheme}>
     <ButtonNext className={buttonnext.small}>small</ButtonNext>
</div>
```

### Current workaround

Problem disappears if I disable rootScope in webpack stylable plugin. 

### Questions

1. Is this the right way to do? If I will go with rooScope disabled - then I will need to ask yoshi team to modify common webpack config where stylable webpack has rooScope: true. Will this affect somehow in a bad way other components?

2. Maybe there are other ways how can I use theming on components? Maybe importing button into the `theme.st.css` and from `js` components just always import everything from `theme.st.css`? 

### Example

https://github.com/wix/wix-ui/pull/731
