### ISSUE TITLE
CLI: transform a stylesheet and get the `css` output

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable#432]
I could not manage to have an pure `css` output from `stc`.

**Comment by tomrav** [comment]
Could you elaborate a bit on what end result you're expecting?

**Comment by hepiyellow** [comment]
Well the simplest example would be:

If I have this:
> comp.st.css
```css
:vars {
  D10: #123456;
}

.root {
  color: value($D10);
}
```

Then I want to run `tsc` on it and get a file `comp.css`
```css
.root {
  color: #123456;
}
```
