### ISSUE TITLE
Cannot define "-st-extends" inside a scoped selector.

### ISSUE THREAD

**Issue by mykas** [wix/stylable#443]
Usecase:
```css
BackofficeTheme .iconButton {
  -st-extends: Button;
  width: 36px;
  height: 36px;
  border-radius: 18px;
  padding: 0;

  box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  text-align: center;
  
  border: 1px solid;
  outline: none;
  transition: all 100ms linear;

  background-color: value(B10);
  border-color: value(B10);
  color: white;
}
```

Class `.iconButton` will not have states coming from stylesheet `Button`.
Example: https://github.com/wix/wix-ui/pull/803/files#diff-72310212f29eff32c2f3cb7a364f6fdbR17

**Comment by mykas** [comment]
`@customs-selector` defined throws same issues.
```css
@custom-selector :--iconButton BackofficeTheme .iconButton;

:import {
  -st-from: '../../../components/button-next/button-next.st.css';
  -st-default: Button;
}

:--iconButton {
  -st-extends: Button;
  width: 36px;
  height: 36px;
  border-radius: 18px;
  padding: 0;

  box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  text-align: center;
  
  border: 1px solid;
  outline: none;
  transition: all 100ms linear;

  background-color: value(B10);
  border-color: value(B10);
  color: white;
}
```
