### ISSUE TITLE
Feature Request: Requesting ability like Sass `extend`

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable#449]
Well,
Sass `extend` concept is very similar to `-st-extends`.
But `-st-extends` is not allowed on complex selectors, so It can not be applied to the following use-case.

## Typography Use-Case
> Typography.st.css
```css
.text {
  color: black;
}

.text.sizeSmall {
  font-size: 14px;
  line-height: 18px;
}

.text.weightBold {
  font-family: value(fontMedium);
}

```

And now a component (`CompA`) which needs to apply default typography to a specific element
> CompA.st.css
```css
:import {
  -st-from: "../typography.st.css";
  -st-named: text, sizeSmall, weightBold;
} 

.root {
}

.root::label {
  -st-extends: text, sizeSmall, weightBold;
}
```

This doesn't work, since `-st-extends` can not be used in complex selectors.
The only way to implement this is using mixins which is creating redundant duplications in the final CSS.
```css
.root::label {
  -st-mixin: text, sizeSmall, weightBold;
}
```

As far as I know, Sass does support `extend` in complex selectors, so I guess it IS possible, right?

If I understand correctly how Sass extend works, the resulting CSS would look like:
```css
.typography_text,
.CompA_root::label {
  color: black;
}

.typography_text.typography_sizeSmall,
.CompA_root::label.CompA_root::label { 
  font-size: 14px;
  line-height: 18px;
}

.typography_text.typography_weightBold,
.CompA_root::label.CompA_root::label {
  font-family: value(fontMedium);
}
```

Of course the `.CompA_root::label.CompA_root::label` could be reduced to `.CompA_root::label`.
