### ISSUE TITLE
Unable to find pseudo element auto-completion for extended comp

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable#453]
> `styleA.st.css`
```css
.compA {
}

.elem1 {
}
```

> `styleB.st.css`
```css
:import {
 -st-from: './styleA.st.css';
 -default: CompA;
}

.compB {
 -st-extends: CompA;
}
```

> `styleC.st.css`
```css
:import {
 -st-from: './styleB.st.css';
 -default: CompB;
}

CompB::
```

The options I get when writing `CompB::` do not include `elem1` from `styleA.st.css`.
But if I change the name of `.compB` to `.root`, then I do see `elem1`.

I understand, that Stylable doesn't know the `compB` is the "root".

**Is there a way to define the name of the "root" class, so that when importing `-st-default` of a stylesheet, it would know which "root" class to rtesolve to?**

**Comment by idoros** [comment]
In your case, `.compB` in the stylesheet `styleB.st.css` is just an internal class. When importing the default export from `styleB.st.css` you get the `root` class (which is not the class `.compB`). So you would get the following selectors available:

```css
CompB::compB::compA {}
CompB::compB::elem1 {}
```
 > notice that `::compB` is the internal part of the `styleB.st.css` component - which is a type of CompA (the `styleA.st.css` stylesheet)

-----

As Stylable does not offer a way to name your root class. It seems like the alternative to your source code would look like this:

```css
/* styleB.st.css */
:import {
 -st-from: './styleA.st.css';
 -st-default: CompA;
}

.root{
 -st-extends: CompA;
}
```
