### ISSUE TITLE
BUG: Class gets wrong namespace

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable#454]
I have a stylesheets A with a class that extends stylesheetB.
Stylesheet A, has a class named `size24`.

In the resulting CSS shown in the storybook (`wix-ui-core`), I see `size24` appearing once with the namespace of A and once with the namespace of B.

Here is the CSS copy&Pasted straight from the DOM:
(I deleted some irrelevant parts to make it shorter
```css
.avatar1878169194--avatar {
}

.avatar1878169194--avatar:not(.avatar1294549426--root)::before {content: "class extending component '.avatar => avatar1878169194--avatar' in stylesheet 'avatar.st.css' was set on a node that does not extend '.root => avatar1294549426--root' from stylesheet 'avatar.st.css'" !important;display: block !important;font-family: monospace !important;background-color: red !important;color: white !important; 
}

.BackofficeTheme324690182--root .avatar1878169194--avatar {
  display: flex;
  justify-content: center;
  align-items: center;

  height: 48px;
  width: 48px;
  border-radius: 30px; 
}

/* Sizes */

.BackofficeTheme324690182--root .avatar1878169194--avatar.avatar1294549426--size24 {
  height: 24px;
  width: 24px;
  border-radius: 12px;
}

.BackofficeTheme324690182--root .avatar1878169194--avatar.avatar1294549426--size18 {
  height: 18px;
  width: 18px;
  border-radius: 12px;
}

/* Sizes text */

.BackofficeTheme324690182--root .avatar1878169194--size24.avatar1878169194--avatar[data-avatar1294549426-contenttype="text"] .avatar1294549426--content,.BackofficeTheme324690182--root .avatar1878169194--size18.avatar1878169194--avatar[data-avatar1294549426-contenttype="text"] .avatar1294549426--content  {
  visibility: hidden;
}
```
## Notice

There is one rule with `.avatar1294549426--size24`
and another with `.avatar1878169194--size24`.

## Analysis
The `avatar1878169194` namespace is of the BASE avatar,
while the `avatar1294549426` is the EXTENSION stylesheet.

I notice that if I define a rule like this:
```css
.size24 {
  visibility: hidden;
}
```
Then `size24` gets the namespace of the BASE

And If I add this:
```css
.avatar.size24 {
  visibility: hidden;
}
```
Then `size24` gets the the correct namespace of the EXTENSION.

While `.avatar` is defined like this:
```css
:import {
  -st-from: '../../../components/avatar/avatar.st.css';
  -st-default: Avatar;
}

.avatar {
  -st-extends: Avatar;
}
```

## Env Details:
```
➜  wix-ui-core git:(avatar/add_img_fallback) ✗ qnm stylable
stylable
└── 5.4.11
➜  wix-ui-core git:(avatar/add_img_fallback) ✗ qnm @stylable/core
@stylable/core
└── 0.1.13
```
