### ISSUE TITLE
support identical selectors

### ISSUE THREAD

**Issue by idoros** [wix/stylable#49]
At the moment selectors with same value are merged:
```css
.a { color:green; }
.b { color:red; }
.a { background:purple; }
```
will invalidly transform to:
```css
.a { color:green; background:purple; }
.b { color:red; }
```
