### ISSUE TITLE
Async import stylesheet wrong depth 

### ISSUE THREAD

**Issue by idoros** [wix/stylable#611]
Stylesheet that is called through an async import get lower depth and is placed in the wrong order.

In this case:
```js
/* index.js */
import './theme.st.css';
export const asyncLoad = () => import('./async-comp');
```
```js
/* async-comp.js */
import './async-comp.st.css';
```
```css
/* theme.st.css */
:global(body) {
    background: green;
}
```
```css
/* async-comp.st.css */
:global(body) {
    background: red;
}
```

`async-comp.st.css` will receive a depth of **1** and will be placed after the `theme.st.css` rules (in both production and static build!)
