### ISSUE TITLE
Nested classes with mixin does not work

### ISSUE THREAD

**Issue by talh78** [wix/stylable#63]
I have a class and a selector: 
```css
.blue {
    -st-mixin: MyMixin(1, 2, 3);
}
.blue.small {
    -st-mixin: MyMixin(4, 5, 6);
}
```
that I want to bring into the class using nested classes:
```css
.blue {
    -st-mixin: MyMixin(1, 2, 3);
    &.small {
        -st-mixin: MyMixin(4, 5, 6);
    }
}
```

The generated CSS does not activate the mixin with (4, 5, 6) when the small class is also applied (It applies the original, (1, 2, 3) mixin)
