### ISSUE TITLE
pseudo-state custom mapping

### ISSUE THREAD

**Issue by idoros** [wix/stylable#7]
Need a way to define custom mapping in order to support none stylable libs:

CSS API:
```css
/* example-custom.css */
.root{
    -sb-states: toggled(".on"), loading("[data-spinner]");
}
.root:toggled { color:red; }
.root:loading { color:green; }
```

CSS OUTPUT:
```css
/* namespaced to example-custom */
.root.on { color:red; }
.root[data-spinner] { color:green; }
```
