### ISSUE TITLE
support multiple selectors in createClassSubsetRoot

### ISSUE THREAD

**Issue by barak007** [wix/stylable#71]
source:
```css
.a { 1 }
.a:hover { 2 }
.a, .b, .a .c { 3 }

.x {
    -st-mixin: a;
}
```

target:
```css
.a { 1 }
.a:hover { 2 }
.a, .b, .a .c { 3 }

.x { 1 } 
.x:hover { 2 } 
.x, .x .c { 3 } /* .b is removed since its not part of the mixin '.a' */
```

`.x, .x .c { 3 }` - not outputted today - bug
