### ISSUE TITLE
@st-scope'd component selector issues false diagnostics

### ISSUE THREAD

**Issue by AviVahl** [wix/stylable#714]
```css
@st-scope Theme {
    MyComp::myPanel .someClass {
        background: black;
    }
}
```
above issues a diagnostic for `.someClass` saying:

> unscoped class "someClass" will affect all elements of the same type in the document
