### ISSUE TITLE
Mixin parameter commas issues

### ISSUE THREAD

**Issue by idoros** [wix/stylable#759]
This is related to the [Mixin syntax limitation](https://github.com/wix/stylable/issues/280) - detecting commas as part of the argument.

**Extra comma** causes a build error:
```css
.mixInto {
    -st-mixin: mix(
        varA yellow, /*(node:14008) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined*/
    );
}
```
**Missing comma** causes the `value1+key2+value2` to be inserted as the first value and completely miss the value after the missing comma:
```css
.mixInto {
    -st-mixin: mix(
        varA yellow
        varB blue
    );
}
/*
varA will equal `yellow/n/t/tvarB blue` completely ignoring var B
*/
```

It's been like this for a while now, but it's difficult to work with and I wonder if we can think of a solution to resolve this. At the minimum allowing for the extra comma will cause less problems when adding new arguments, and forgetting to add the extra comma (every time).
