### ISSUE TITLE
Custom value definition error

### ISSUE THREAD

**Issue by idoros** [wix/stylable#760]
Error in custom value definition is not reflected in build - just ignored.

```
/*custom-val.js*/
throw new Error('show me to user!')
```

Using this custom-val shows no errors in build and any declaration generated by it will simply be replaced by its source value with no indication of a problem.

```css
:import {
    -st-from: "./custom-val";
    -st-default: CustomVal;
}
:vars {
    varA: CustomVal(a red, b green, c blue) doesn't matter because value will throw!;
}
.mixInto {
    --customValFull: value(varA);
}
```

will be transformed to:
```css
.file__mixInto {
    --customValFull: CustomVal(a red, b green, c blue) doesn't matter because value will throw!;
}
```

Maybe Stylable should insert a warning comment when encountering problematic declarations?
