### ISSUE TITLE
Custom value named strategy error

### ISSUE THREAD

**Issue by idoros** [wix/stylable#761]
When mistakenly passing argument list into  `CustomValueStrategy.named`, an unhandled error `Cannot read property 'type' of undefined` is thrown and breaks the build (originating from [this line](https://github.com/wix/stylable/blob/408a01783c70c35c2d2e28771e85d76f6851e821/packages/core/src/custom-values.ts#L94)):

```js
/*custom-val.js*/
const { createCustomValue, CustomValueStrategy } = require('@stylable/core');

module.exports = createCustomValue({
  processArgs: (node, customTypes) => {
    return CustomValueStrategy.named(node, customTypes);
  },
  createValue: args => {
    return args;
  },
  getValue: (value, index) => value[index]
});
```

```css
:import {
    -st-from: "./custom-val";
    -st-default: CustomVal;
}
:vars {
   /*passing arguments instead of named params*/
    varA: CustomVal(a, b, c);
}

.mixInto {
    --customValFull: value(varA);
}
```

Maybe instead it could gracefully just break the custom value parameter and inform the developer of it.

[playground](https://wixplosives.github.io/stylable-playground/#state=%28%27files%21%28B%21%27%2540M-import%2520X%2520from%2520%2522.JQ%2522%253B4%253AvNsH0%2520%252F*passing%2520Nguments%2520inMead%2520of%2520named%2520pNams*%252F07vNA5X%257Ba6b6c84%2944.mixIntoH07--c1Full5vD%257BvNA84%29%27%7EJQ.js%21%27conMHE6G%2520%29ROquiO%257B%2522%2540MylableJO%2522844module.exports9E%257B%280processArgs532G.named3LcOPVD5Ngs2NgsLgetVD5%257BvD6K%257DU%2520vD%255BK%255D4%298%27%29%7Eselected%21B%27%290471WVal2UH07Oturn%25203%257BnoQ6cWTypes%257D4%255Cn5%253A%25206%252C%25207%2520%25208%257D%253BR%253DB%27%252FK.M.cssDalueE%2520cOPXueGXueStrPgyH%2520%28J%252FcoKinQxL%253B0%29%252C0MstNarOrePateQdeR9%2520U9%253EWuMomXC1%2501XWURQPONMLKJHGEDB9876543210_)
