### ISSUE TITLE
Custom value to mixin

### ISSUE THREAD

**Issue by idoros** [wix/stylable#762]
Custom values are great, but I'm missing the capability of passing them into mixins (both CSS & JS).

For example I would like to use the stBorder custom value to define a border:
```css
:vars {
    myBorder: stBorder(5px, solid, salmon);
}
```

and then pass the value into a mixin so it can choose how to use it.

So I might have a CSS mixin that accepts a "boxed" border and uses its parts:

```css
:vars {
    border: stBorder(5px, solid, salmon);
}
.cssMix {
    border-top: value(border);
    box-shadow: 5px 5px 2px 1px value(border, color);
}
```

currently there is no way to pass the untransformed value in:

```
:vars {
    myBorder: stBorder(5px, solid, salmon);
}
.root {
    -st-mixin: cssMix(border ?myBorder?);
}
```

The same capability with JS mixin would pass in the actual custom-value "value", or even better the custom value "instance", allowing to call custom methods that it might expose.
