### ISSUE TITLE
font loading bug

### ISSUE THREAD

**Issue by idoros** [wix/stylable#764]
`@font-face` rule needs to be defined like this:

```css
@font-face {
    font-family: MyCustomFont;
    src: url(fonts/my-font.eot);
    src: url(fonts/my-font.eot) format('opentype'),
        url(fonts/my-font.woff) format('woff'),
        url(fonts/my-font.ttf) format('truetype');
    font-weight: normal;
    font-style: normal;
}
```

When writing in Stylable source we have 2 issues:
- `format()` is unknown to Stylable: `cannot find native function or custom formatter called format`.
- the string quotation marks are stripped from the format value - so the browser ignores and doesn't even try to load the font.

 ```css
@font-face {
    font-family: MyCustomFont;
    src: url(./fonts/my-font.eot);
    src: url(./fonts/my-font.eot) format(opentype), /*missing quotations*/
        url(./fonts/my-font.woff) format(woff), /*missing quotations*/
        url(./fonts/my-font.ttf) format(truetype); /*missing quotations*/
    font-weight: normal;
    font-style: normal;
}
```
-----
My current workaround is to have a `custom-value` just for the format string:
```js
/*format-hack.js*/
const { createCustomValue } = require('@stylable/core');
module.exports = createCustomValue({
  processArgs: (_node, _customTypes) => {
    return {};
  },
  createValue: _args => {
    return {};
  },
  getValue: (_value, type) => `format('${type}')`
});
```
usage:
```css
:import {
    -st-from: "./format-hack";
    -st-default: aWayToPrintFont;
}
@font-face {
    font-family: MyCustomFont;
    src: url("./fonts/my-font.eot");
    src: url("./fonts/my-font.eot?#iefix") value(customFormat, opentype),
        url("./fonts/my-font.woff") value(customFormat, woff),
        url("./fonts/my-font.ttf") value(customFormat, truetype);
    font-weight: normal;
    font-style: normal;
}
```
-----
Also when using Webpack you need the `file-loader` to handle the font file resolving. Docs can benefit from a  `fonts in Stylable` explanation.
