### ISSUE TITLE
CSS fragments order - depth collisions!

### ISSUE THREAD

**Issue by idoros** [wix/stylable#774]
We want to separate CSS fragments into logical modules, like components, variants, resetters, themes and others to help with maintainability and configuration.

## The problem

CSS order matters **(!)** and eventually we need to flatten out our fragments in some fixed order.

For example, when an `Item` component is passed to a `Container` component. The container might override the item CSS and we want the container CSS fragment to be placed `after` the item component.

So when the `Container` stylesheet overrides CSS of the child `Item` then the order becomes important - **Container CSS before Child CSS will not override**.

> \* Not going into complex specificity overrides that will probably need best practices before CSS4.

One way to resolve the order, used by `style-loader`, is to sort the CSS fragments by the dependency order from Webpack. So the order of imports in a module decides on the sort of the CSS fragments imported by it. And when a developer encounters a case where `Container` CSS needs to be placed **after** `Child` CSS, but doesn't, then a simple switch of the imports can* fix the order problem. 

### Problem with import order hinting

With this approach any previous module in the `build` dependency chain may override the order, blocking the "swap" (or breaking when changed as a later time).

This issue seems like an edge case, however it becomes a very legitimate case when considering Stylable goal is to provide a way to style **reusable** components:
- changing import order shouldn't be a breaking change
- and importing something shouldn't break your CSS if it didn't add any new CSS.

## Currently in Stylable

To avoid this the import order problem, Stylable tries to understand the real dependencies between stylesheets. So that a `Gallery` that might override some composed `Button` style will always be placed after it.

And to achieve this Stylable orders the stylesheets (CSS fragments) according to a `depth` value that is assigned to every stylesheet and will result being higher then the max `depth` value (+1) of its composed dependencies.

> In addition, giving the component file a mirror name of the stylesheet will result in it's dependencies max `depth` value (+1) to be maxed with the result. e.g. `comp.st.css & comp.js` (or `.ts` if you use Typescript).

The promise is that the order of overriding CSS fragments will be sorted correctly under a `depth` value, however there is no guarantee for the order between fragments of the same `depth`, since they don't override.

Going back to the **`Container/Item` issue**, both components CSS fragments get a `depth=1` since both compose no other components, and because order between the same `depth` layer is not guaranteed, there is no way to control the order (*There is a bug in this [thread](https://github.com/wix/stylable/issues/770#issuecomment-529335775) with inconsistent output between machines*).

> another benefit not extended here is that CSS fragments loaded dynamically at `runtime` knows between which of the already loaded fragments they needs to be inserted into. And how the separating insertion points into depth helps to publish 3rd party stylable components.

## Solution 1 - internal depth sort

Sort each `depth` layer according to the build module dependency tree, however this is a very fragile fix since there is still the [problem with import order hinting](#Problem-with-import-order-hinting) and in addition there is a chance that one of the component will change its `depth` and break the style in a way that cannot be simply managed by import order.

## Solution 2 - max depth flag

**Today** when an `App` renders a `Container` the result are:

```css
/*[depth=1] container.st.css*/
.container__root {}
.container__item {}

/*[depth=2] app.st.css*/
```

When the app renders a button into the container, both container and button might get the same `depth` and its order is not guaranteed:

```css
/*[depth=1] container.st.css*/
.container__root {}
.container__item {}
/*[depth=1] button.st.css*/
.button__root {}

/*[depth=2] app.st.css*/
```

Now if the container passes the `item` class to the child `Button` the CSS might not override:

```css
/*[depth=1] container.st.css*/
.container__root {}
.container__item { color: green; }
/*[depth=1] button.st.css*/
.button__root { color: red; /*after wins!*/}

/*[depth=2] app.st.css*/
```

The `Container` component view/logic actually accepts child fragments to render within itself. If it knew the possible child elements types we could have extended them in Stylable and resolve this, but the component doesn't know the child type and so we are missing some order information.

We can solve this by allowing the `Container` to indicate that it might affect components that it doesn't know about and give it a different way to resolve its CSS fragment `depth` value:

```css
/*[depth=1] button.st.css*/
.button__root { color: red;}

/*[depth=2] container.st.css*/
.container__root {
    -st-generic: true;
}
.container__item { color: green; }

/*[depth=3] app.st.css*/
```

The `-st-generic` declaration kept the container `depth` resolution to a second phase in which the value is resolved to be greater then all CSS fragments `depth` that don't extend it `directly`, it also increased the dependent fragments `depth` to accommodate the newly inserted layer.

There are 2 edge case to this:
1. circular dependency between components - similar to today, eventually something needs to be last.
2. generic components of the same depth containment.

Both of which exist in CSS and are eventually resolved by wrapping components, or overriding styles from the top level of the deployed application.

**Comment by idoros** [comment]
Talking to @nadavov, he suggested a specificity best practice approach can be taken by generic components like the `Container`.

In  our case we had the `Container` and the `Button` sorted into the same layer with potential colliding classes:

```css
/*[depth=1] container.st.css*/
.container__root {}
.container__item { color: green; }
/*[depth=1] button.st.css*/
.button__root { color: red; /*after wins!*/}
```

By increasing the `.item` rule specificity, the `Container` can override the item in simple cases:

```css
/*[depth=1] container.st.css*/
.container__root {}
.container__root > .container__item { color: green;  /*specificity wins!*/}
/*[depth=1] button.st.css*/
.button__root { color: red;}
```

So the rule here is that unknown type overrides should always add the `.root` to increase specificity and win over another component. 

However, even following this rule, there are inconsistencies caused by the order inside the each layer:

```css
/*[depth=1] container.st.css*/
.container__root > .container__item { color: green;}
/*[depth=1] button.st.css*/
.button__root:hover { color: purple; /*specificity + order wins!*/}
```

and swapped:

```css
/*[depth=1] button.st.css*/
.button__root:hover { color: purple;}
/*[depth=1] container.st.css*/
.container__root > .container__item { color: green; /*specificity + order wins!*/}
```
