### ISSUE TITLE
additional argument warning for custom value

### ISSUE THREAD

**Issue by idoros** [wix/stylable#779]
Using a [custom value](https://stylable.io/docs/references/variables#advanced-variable-types) which **works as expected** still warns about the second argument:

```css
:import {
    -st-from: "./color-custom-value";
    -st-default: hue;
}
:vars {
    mainColor: hue('170');
}
.root {
    color: value(mainColor, dark);
    /*
Stylable: file.st.css:9:6: value function accepts only a single argument: "value(mainColor, dark)"
    */
}
```
