### ISSUE TITLE
Cannot find formatter warnings

### ISSUE THREAD

**Issue by nullsage** [wix/stylable#848]
There are a lot of cannot find formatter warnings happening when i compile my project.

`format`
`constant`
`env`
`local`

example:
```css
    @font-face {
        font-family: 'Material Icons';
        font-style: normal;
        font-weight: 400;
        src: local('Material Icons'), local('MaterialIcons-Regular'), 
        url(/material-design-icons/iconfont/MaterialIcons-Regular.woff2) format('woff2'), 
        url(/material-design-icons/iconfont/MaterialIcons-Regular.woff) format('woff'), 
        url(/material-design-icons/iconfont/MaterialIcons-Regular.ttf) format('truetype');
}
```

I did not see anything in the docs about formatting these or not using these. Will this be fixed in the near future?
