### ISSUE TITLE
Error with mixins in next version

### ISSUE THREAD

**Issue by idoros** [wix/stylable#867]
2.4.1-alpha-0 has a regression bug with mixins:

```css
/*comp.st.css*/
.root {}

/*variant.st.css*/
:import {
    -st-from: './comp.st.css';
    -st-default: Comp;
}
.root {
    /* will not error without the extends*/
    -st-extends: Comp; 
}

/*theme.st.css*/
:import {
    -st-from: './comp.st.css';
    -st-default: Comp;
}
:import {
    -st-from: './variant.st.css';
    -st-default: Variant;
}
@st-scope .root {
    Comp {
        -st-mixin: Variant; /* ERROR: Cannot read property 'walkRules' of undefined */
    }
    div {
        /*will error on any element*/
        -st-mixin: Variant; /* ERROR: Cannot read property 'walkRules' of undefined */
    }
}
```
