### ISSUE TITLE
Selector list with custom elements fail to transform in "next" version

### ISSUE THREAD

**Issue by idoros** [wix/stylable#869]
This is a regression from `2.4.0`.

```css
/*comp.st.css*/
.partA {}
.partB {}

/*variant.st.css*/
:import {
    -st-from: "./comp.st.css";
    -st-default: Comp;
}
.root {
    -st-extends: Comp;
}
.root::partA, .root::partB {} /* Warning unknown pseudo element "partB" */

/*entry.st.css*/
:import {
    -st-from: "./variant.st.css";
    -st-default: Variant;
}
.root {
    -st-mixin: Variant;
}
```

`::partB` is not be transformed correctly when mixed in
