### ISSUE TITLE
Improve support for multiple selectors in custom-selectors

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#890]
In cases where a custom-selector which contains multiple selectors is used in a complex selector, that selector should be properly scoped to account for all possible permutations.

Example:
```css
@custom-selector :--example .a, .b;
    
.root:has(:--example) {
    color: blue;
}
```

Should transpile to:
```css
.root:has(.a), .root:has(.b) {
    color: blue;
}
```

Current implementation only accounts for the first selector.
