### ISSUE TITLE
Webpack: Cannot load assets from node modules

### ISSUE THREAD

**Issue by simast** [wix/stylable#908]
Is there a feature in Stylable webpack plugin that allows loading assets from node modules? In css-loader you can use tilde (`~`) character for this.

Would it be possible to add support for tilde to Stylable webpack plugin as well? As something like this currently does not work as expected:

```css
.root {
  background-image: url('~wix-ui-icons-common/ArrowRight.svg');
}
```
